Fixed exceptions poppuing up in AdminGUI and redirection
CONNECT-Solution/CONNECT pull request #1340
Opened 2016-10-07 19:43 UTC by TabassumJafri

1. Fixed exception popping up when user clicks on Remote Gateway List sorting links.
2. Fixed sorting on Remote gateway List. Now very click will fetch data from db and sort it as well.
3. Added null check in afterPhase method of UserAuthorizationListener. FacesContext and FacesContext.getViewRoot() were null causing a NullPointer.
4.  Fixed CustomExceptionHandlerWrapper to redirect to CustomError page when malformed http header injection is detected. Also user is now getting redirected to login page when the session expired with an error message.

reviewer: @mhpnguyen

2016-10-07 20:11 UTC, mhpnguyen requested changes

2016-10-07 20:11 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/exceptionhandler/CustomExceptionHandlerWrapper.java
> +                        "An Exception occurred while performing the requested function.", ""));
possible to convert into message properties or java constant so that we can change text message later

2016-10-07 20:11 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/exceptionhandler/CustomExceptionHandlerWrapper.java
> +                        "Your session has expired, please login!", ""));
Convert into java constant for string or put into properties

2016-10-11 17:26 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/exceptionhandler/CustomExceptionHandlerWrapper.java
> +                        "An Exception occurred while performing the requested function.", ""));
Moved exception message  to a constant class.  Created a backlog item to introduce ResourceBundle to admingui.

2016-10-11 21:19 UTC, mhpnguyen commented
retest this please

2016-10-11 21:22 UTC, mhpnguyen commented
ok to test

2016-10-12 13:52 UTC, mhpnguyen commented
ok to test

2016-10-12 14:02 UTC, mhpnguyen commented
test this please

2016-10-12 14:18 UTC, mhpnguyen approved these changes

2016-10-12 14:23 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/exceptionhandler/CustomExceptionHandlerWrapper.java
> +                        "Your session has expired, please login!", ""));
was fixed in previous commit.

2016-10-12 15:19 UTC, merged