Fhac 1312 - Refactored code to resolve Sonar findings for CXF_POC
CONNECT-Solution/CONNECT pull request #1358
Opened 2017-01-27 15:26 UTC by mikhelamdex

Refactoring the following classes in gov.hhs.fha.nhinc.callback.cxf.largefile package:
CONNECTTimestamp.java
TimestampValidator.java

@mhpnguyen @jsmith2 @sjarral112 - Please review

2017-01-27 16:34 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/CONNECTTimestamp.java
> +            if (LOG.isDebugEnabled()) {
Stylistic suggestion -- usually, "isDebugEnabled()" should be reserved for instances where there is a costly calculation going into the log statement.

2017-01-27 17:45 UTC, mhpnguyen requested changes

2017-01-27 17:45 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/CONNECTTimestamp.java
> +                LOG.debug("Validation of Timestamp: Everything is ok");
this comment and condition doesn't look right.  Please verify the logic

2017-01-27 17:45 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/CONNECTTimestamp.java
> +            if (LOG.isDebugEnabled()) {
agreed.  Please remove isdebugenable in the file

2017-01-27 17:45 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/TimestampValidator.java
> +
remove extra line

2017-01-27 17:45 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/TimestampValidator.java
> +    private void validate(CONNECTTimestamp timeStamp, RequestData data) throws WSSecurityException {
consider to put javadoc in file

2017-01-27 17:45 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/TimestampValidator.java
>              LOG.warn("Failed to determine timestamp future TTL in gateway.properties, will use default value: {}",
consider to use warn or trace. It doesn't make sense to log twice with different message

2017-01-27 17:45 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/TimestampValidator.java
> +                pae.getLocalizedMessage());
Please see comment above

2017-01-30 17:51 UTC, mhpnguyen commented
Endorse for merging without comment

2017-01-30 18:08 UTC, mhpnguyen approved these changes

2017-01-30 21:25 UTC, sjarral112 commented
Tested for Code format, Code practice and simplicity, no further change required.

2017-01-31 14:57 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/CONNECTTimestamp.java
> +            date.setTime(invocationTime + futureTimeToLive * 1000);
I don't follow the logic here.  Wouldn't the setTime on line 93 always be overridden by setTime on line 103?

2017-01-31 15:04 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/largefile/CONNECTTimestamp.java
> +            date.setTime(invocationTime + futureTimeToLive * 1000);
Nevermind.  The confusion is that the same variable is used to represent two values, the value of the future time (so it's not created in the future) and of the past time (so it's confirmed that it isn't created too far in the past.  We might want to clean this up for clarity and appropriate variable naming.  Using a variable name like "date" isn't very clear.

2017-01-31 20:18 UTC, jsmith2 approved these changes

2017-01-31 20:51 UTC, merged