FHAC-1311-Revised
CONNECT-Solution/CONNECT pull request #1370
Opened 2017-02-17 17:54 UTC by sjarral112

Files modified were -

src/main/java/gov/hhs/fha/nhinc/callback/SamlConstants.java
  src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
  src/main/java/gov/hhs/fha/nhinc/callback/cxf/CXFSAMLCallbackHandler.java
 src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2AllowNoSubjectAssertionSpecValidator.java
src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2ExchangeAuthFrameworkValidator.java
src/test/java/gov/hhs/fha/nhinc/callback/cxf/Saml2ExchangeAuthFrameworkValidatorTest.java

2017-02-17 18:52 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +                    SamlConstants.SECURITY_ASSERTION_ISSUER_FORMAT + "" + SamlConstants.URN_OASIS_NAMES + "" + "and"
Should there be a space within the open/close quotes?  Otherwise, there are unnecessary string concatenations within this statement.

2017-02-17 18:55 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +        return saml2SpecValidator;
This can be simplified to "return null".

2017-02-17 18:56 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CXFSAMLCallbackHandler.java
> +                    custAssertion = getCustAssertion(obj);
Unnecessary separation of declaration and assignment.

2017-02-17 18:58 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2AllowNoSubjectAssertionSpecValidator.java
> +        if (assertion.getStatements() == null || assertion.getStatements().isEmpty()) {
Can this also be converted to use a single emptiness check?

2017-02-17 19:46 UTC, mhpnguyen requested changes

2017-02-17 19:46 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +        Collection<Saml2ExchangeAuthFrameworkValidator> saml2SpecValidator;
Consider to remove this method and start to use Collections.emptyList to comply sonarqube violation.

2017-02-17 19:46 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +        if (!methods.isEmpty()) {
if List has option to use "isNotEmpty", then consider to use for easy to read.

2017-02-17 19:46 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2AllowNoSubjectAssertionSpecValidator.java
> +        if (!assertion.getAuthnStatements().isEmpty() && assertion.getSubject() == null) {
Consider to use CollectionUtils.isNotEmpty

2017-02-17 19:46 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2AllowNoSubjectAssertionSpecValidator.java
> +        if (!assertion.getAuthzDecisionStatements().isEmpty() && assertion.getSubject() == null) {
Consider to use CollectionUtils.isNotEmpty

2017-02-17 19:46 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2AllowNoSubjectAssertionSpecValidator.java
> +        if ((assertion.getAttributeStatements() == null || assertion.getAttributeStatements().isEmpty())
Consider to use empty check in Collection.

2017-02-17 19:46 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2AllowNoSubjectAssertionSpecValidator.java
> +        if ((assertion.getAuthzDecisionStatements() == null || assertion.getAuthzDecisionStatements().isEmpty())
Consider to use empty check in Collection

2017-02-17 19:46 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/callback/cxf/Saml2ExchangeAuthFrameworkValidatorTest.java
> +        /*
Remove the comment block if don't use

2017-02-17 21:57 UTC, mhpnguyen requested changes

2017-02-17 21:57 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2AllowNoSubjectAssertionSpecValidator.java
> +            && (assertion.getAuthnStatements() == null || assertion.getAuthnStatements().isEmpty())) {
consider to use CollectionUtils

2017-02-17 21:57 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2ExchangeAuthFrameworkValidator.java
> +            emailValidator(value);
rename to comply java standard name convention.  validateEmail

2017-02-17 21:57 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/Saml2ExchangeAuthFrameworkValidator.java
> +            partsValidator(value);
same thing here

2017-02-17 21:57 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +            if (!StringUtils.isBlank(issuer.getSPProvidedID())) {
Use STringUtils.isNotBlank instead of !StringUtils.isBlank

2017-02-17 21:57 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +            if (!StringUtils.isBlank(issuer.getNameQualifier())) {
Use STringUtils.isNotBlank instead of !StringUtils.isBlank

2017-02-21 14:04 UTC, mhpnguyen approved these changes

2017-02-21 14:04 UTC, merged