Fhac 1353
CONNECT-Solution/CONNECT pull request #1375
Opened 2017-03-06 21:29 UTC by TabassumJafri

Reduced the number of jars in WAS pom .

@mhpnguyen  and @sjarral112

2017-03-06 21:34 UTC, mhpnguyen requested changes

2017-03-06 21:34 UTC, mhpnguyen commented on Product/Production/Deploy/was/pom.xml
>  						lib/javax.servlet-api-3.0.1.jar,
Can you remove tab space?

2017-03-06 21:42 UTC, mhpnguyen approved these changes

2017-03-07 15:31 UTC, sjarral112 approved these changes
Changes approved to be merged

2017-03-07 15:34 UTC, merged