Fhac 1408 - Remove forge rock dependencies
CONNECT-Solution/CONNECT pull request #1389
Opened 2017-04-07 16:24 UTC by jsmith2

DO NOT MERGE.

This is removal from CONNECT repo, adding removed projects to CONNECT Plugin repo.

2017-04-25 17:09 UTC, mhpnguyen requested changes
Please see my inline comments.  In additional to that, we also need to update PolicyEngineProxyConfig.xml and other configuration to reflect remove files

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Install/WildFly/templates/standalone.conf.bat
> +set "JAVA_OPTS=%JAVA_OPTS% -Dnhinc.properties.dir=%JBOSS_HOME%/modules/system/layers/base/org/connectopensource/configuration/main"
(optional). This fix resolves quick deployment for wildfly.  However, this PR deals with forgerock issue?  Should we separately this into another PR so that each have their own purpose

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Adapters/DocumentQuery_a0/src/main/java/gov/hhs/fha/nhinc/docquery/adapter/AdapterDocQueryOrchImpl.java
> +       return queryResponse;
This method does nothing. Suggest to remove them

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Adapters/DocumentQuery_a0/src/test/java/gov/hhs/fha/nhinc/docquery/adapter/AdapterDocQueryOrchImplTest.java
> +
remove new line

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Adapters/DocumentQuery_a0/src/test/java/gov/hhs/fha/nhinc/docquery/adapter/AdapterDocQueryOrchImplTest.java
>  }
insert new line

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdapterWeb/pom.xml
>          </dependency>
Unable to comment-inline this block.  Suggest to remove PolicyEngineCore dependency since we don't use it

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Gateway/DocumentQuery_30/pom.xml
> +            <artifactId>DocRegistryCore</artifactId>
Do we need to add this dependency since we did not include previously?

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Adapters/DocumentQuery_a0/src/main/java/gov/hhs/fha/nhinc/docquery/adapter/AdapterDocQueryOrchImpl.java
> +       return queryResponse;
We also have the similar class in DocumentQueryCore.  Suggest to consolidate them to reduce duplication.

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Services/pom.xml
>          <module>PolicyEngineCore</module>
Does we still need PolicyEngineCore

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Services/PolicyEngineCore/pom.xml
> +<!--        <dependency>
remove it

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Services/DocumentRetrieveCore/src/main/java/gov/hhs/fha/nhinc/docretrieve/adapter/AdapterDocRetrieveOrchImpl.java
>      protected RetrieveDocumentSetResponseType callRedactionEngine(RetrieveDocumentSetRequestType retrieveRequest,
Similar issue with AdapterDocQueryOrchImpl. Remove method callRedationEngine if we don't use or serve no purpose

2017-04-25 17:09 UTC, mhpnguyen commented on Product/Production/Services/DocumentQueryCore/src/main/java/gov/hhs/fha/nhinc/docquery/adapter/AdapterDocQueryOrchImpl.java
>      protected AdhocQueryResponse callRedactionEngine(AdhocQueryRequest queryRequest, AdhocQueryResponse queryResponse,
Remove callRedactionEngine if we don't use it

2017-04-25 18:41 UTC, TabassumJafri requested changes
Need to update internalConnectionInfo.xml to reflect changes done in this PR

2017-04-25 18:41 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdapterWeb/src/main/java/gov/hhs/fha/nhinc/redactionengine/adapter/AdapterComponentRedactionEngine.java
> -public class AdapterComponentRedactionEngine
Need to remove the adapterredactionengine from internalConnectionInfo.xml as well

2017-04-25 18:41 UTC, TabassumJafri commented on Product/Production/Services/AdapterAuthenticationCore/src/main/java/gov/hhs/fha/nhinc/adapterauthentication/proxy/AdapterAuthenticationProxyObjectFactory.java
> -    private static final String BEAN_NAME_ADAPTER_AUTH = "adapterauthentication";
Need to remove adapterAuthentication from internalConnectionInfo.xml

2017-04-25 18:41 UTC, TabassumJafri commented on Product/Production/Services/AdapterAuthenticationCore/src/main/java/gov/hhs/fha/nhinc/adapterauthentication/proxy/AdapterAuthenticationProxyObjectFactory.java
> -    private static final String BEAN_NAME_ADAPTER_AUTH = "adapterauthentication";
Need to remove adapterAuthentication from internalConnectionInfo.xml and the corresponding wsdl

2017-04-25 18:41 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdapterWeb/src/main/java/gov/hhs/fha/nhinc/redactionengine/adapter/AdapterComponentRedactionEngine.java
> -public class AdapterComponentRedactionEngine
Need to remove the adapterredactionengine from internalConnectionInfo.xml and the appropriate wsdl as well

2017-04-26 19:45 UTC, jsmith2 commented on Product/Install/WildFly/templates/standalone.conf.bat
> +set "JAVA_OPTS=%JAVA_OPTS% -Dnhinc.properties.dir=%JBOSS_HOME%/modules/system/layers/base/org/connectopensource/configuration/main"
Yes.  I think I'll submit a separate PR for this.

2017-04-26 19:46 UTC, jsmith2 commented on Product/Production/Adapters/General/CONNECTAdapterWeb/pom.xml
>          </dependency>
Ok.  Will look into this.

2017-04-26 19:50 UTC, jsmith2 commented on Product/Production/Services/pom.xml
>          <module>PolicyEngineCore</module>
yes.  only removed part of policyenginecore.

2017-04-26 19:51 UTC, jsmith2 commented on Product/Production/Services/AdapterAuthenticationCore/src/main/java/gov/hhs/fha/nhinc/adapterauthentication/proxy/AdapterAuthenticationProxyObjectFactory.java
> -    private static final String BEAN_NAME_ADAPTER_AUTH = "adapterauthentication";
Good catch on all the internalconnectioninfo services I need to remove.  I'll update that and commit.

2017-04-26 19:52 UTC, jsmith2 commented
I created a few code stubs, so that it would be easy for anyone to come in and know where to insert the logic for reaching the new plugin.  I'll comment them out and add additional comments instead.

2017-05-03 16:57 UTC, jsmith2 commented on Product/Production/Adapters/General/CONNECTAdapterWeb/pom.xml
>          </dependency>
We use PolicyEngineCore still in AdapterWeb.  We don't use redaction engine, so I removed that.

2017-05-17 20:09 UTC, TabassumJafri approved these changes
Approving without any comments

2017-05-19 13:54 UTC, mhpnguyen approved these changes
Endorse for merging.

2017-05-22 15:10 UTC, merged