FHAC-1443: Add more Junit test
CONNECT-Solution/CONNECT pull request #1392
Opened 2017-04-26 18:39 UTC by balmeeki

Added test clas forAdhocQueryTransformHelper
@sjarral112 (optional): feel free to review

2017-04-26 21:39 UTC, balmeeki reviewed
Added test cases and removed unused imports

2017-04-27 13:47 UTC, mhpnguyen requested changes
In additional to that, please make sure to follow https://connectopensource.atlassian.net/wiki/display/CONNECTWIKI/Coding+templates+and+formatters

2017-04-27 13:47 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +//import gov.hhs.fha.nhinc.common.nhinccommon.AssertionType;
Remove comment import if we don't use it

2017-04-27 13:47 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +     //   eventA.getDirection()= "inbound";
Remove if we don't use them

2017-04-27 13:47 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +     //   eventA.getDirection()= "inbound";
similar as above

2017-04-27 13:47 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +     //   eventA.getDirection()= "inbound";
Remove if we don't use it

2017-05-01 13:01 UTC, TabassumJafri requested changes

2017-05-01 13:01 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +import org.slf4j.Logger;
Unused Imports

2017-05-01 13:01 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +import java.util.List;
Unused Import

2017-05-01 13:01 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +package gov.hhs.fha.nhinc.transform.policy;
Connect License missing

2017-05-01 13:01 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +        assertNotNull(result);
Please check if the result object is valid or not for inbound.

2017-05-01 13:01 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +    }
assert for valid outbound object

2017-05-03 16:46 UTC, TabassumJafri commented
Closing the pull request as another PR is up for the same ticket --> https://github.com/CONNECT-Solution/CONNECT/pull/1395

2017-05-03 16:46 UTC, closed without merging