Added test file AdhocQueryTransformHelper.java
CONNECT-Solution/CONNECT pull request #1395
Opened 2017-05-02 18:50 UTC by balmeeki

Added test file for AdhocQueryTransformHelper.java" Reviewers: @sjarral112 @TabassumJafri @jsmith2 @mhpnguyen

2017-05-02 19:18 UTC, TabassumJafri requested changes

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +import org.junit.Ignore;
unused import

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        // Assert Resource Session
declare 12345566 as a constant variable and then use it in your test class

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        AttributeType attributeType = subjectType.getAttribute().get(1);
Reason for not asserting on subjectType.getAttribute().get(0)

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        AttributeType attributeType = subjectType.getAttribute().get(1);
Reason for not asserting on subjectType.getAttribute().get(0)?

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        AdhocQueryRequestEventType eventA = new AdhocQueryRequestEventType();
Do we need this test? looks redundant

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +    	AdhocQueryTransformHelper instance = new AdhocQueryTransformHelper();
Do we need this test? looks redundant

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +package gov.hhs.fha.nhinc.transform.policy;
Add License information

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        CheckPolicyRequestType result = instance.transformAdhocQueryResponseToCheckPolicy(eventB);
AssertNotNull is not sufficient. Please appropriately assert the object.

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        eventB.setDirection("outbound");
AssertNotNull is not sufficient. Please appropriately assert the object.

2017-05-02 19:18 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        // Assert Resource Session
Declare Constants and then use it in your test class. For instance, declare MESSAGE_ID = 12345566 and then use  MESSAGE_ID where needed .

2017-05-03 13:41 UTC, mhpnguyen requested changes

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +     //   eventA.getDirection()= "inbound";
Remove this comment block if we don't use it.  Please also check other location.

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        AdhocQueryRequestEventType eventA = new AdhocQueryRequestEventType();
Agree with Tabassum or at least rename test method to something like this "testTransformAdhocQueryToCheckPolicy_DefaultOutBound"

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +}
add new line.

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +}
Please see this wiki page for code formatter. 
 https://connectopensource.atlassian.net/wiki/display/CONNECTWIKI/Coding+templates+and+formatters

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +    	AdhocQueryTransformHelper instance = new AdhocQueryTransformHelper();
Remove instance since it is redundancy.

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +    	AdhocQueryTransformHelper instance = new AdhocQueryTransformHelper();
remove instance variable

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +     //   eventA.getDirection()= "inbound";
Remove this comment line

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +     //   eventA.getDirection()= "inbound";
Remove this inline

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +        assertNotNull(result);
Try to reuse other assertion since they are almost identical.

2017-05-03 13:41 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelper.java
> +    private void verifycheckInboundPolicy(CheckPolicyRequestType actualCheckPolicy) {
verifycheckInboundPolicy and verifycheckOutboundPolicy are almost the same except DocumentQueryOut vs DocumentQueryIn.  Try to refactor so we don't duplicate method in here

2017-05-03 17:58 UTC, mhpnguyen requested changes

2017-05-03 17:58 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +        assertNotNull(result);
per @TabassumJafri mention before, we need to assert more on result object.

2017-05-03 17:58 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +        assertNotNull(result);
same as above.

2017-05-03 17:58 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +}
add new line

2017-05-03 20:52 UTC, jsmith2 commented
You're missing a test for response outbound.

2017-05-03 20:52 UTC, jsmith2 requested changes

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +		assertionTypeTest.setMessageId("12345566");
Why aren't you using the class variable for messageId?

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +		homeCom.setHomeCommunityId("urn:oid:1.1.1.1.1.1.1");
Same here.  There's a class variable for this value.

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +		assertEquals("messageId should not change", "12345566", assertTypeResult.getMessageId());
Again, using a new string instead of the class variable.

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +		String expectResourceId = "amp;26.489.22";
why didn't we pull out all these strings into class variables?

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +		assertEquals("urn:oid:1.1.1.1.1.1.1", attributeType.getAttributeValue().get(0).getContent().get(0));
Not using class variable that already represents this value.

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +	public void testTransformAdhocQueryToCheckPolicy() {
Test method name is poor.  What's this testing?  Request or response?

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +		String direction = "DocumentQueryOut";
Consider changing your test names for clarity.  should be _RequestOutbound

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +		assertNotNull(actualCheckPolicy);
You have two private methods that seem to do the exact same thing.  Should be able to combine them or combine the similar functionality.

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +	private AdhocQueryTransformHelper instance;
"Instance" is a bad variable name.

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +		assertNull("We should expect null checkPolicyEngine ", result);
You do the same thing twice here.  remove lines 212 and 213.

2017-05-03 20:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +
I don't understand the purpose of the "default" tests.  they don't test anything.

2017-05-05 02:31 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/AdhocQueryTransformHelperTest.java
> +	@Test
I still don't understand the purpose of these default tests other than for coverage.  They don't seem to have any functional testing.

2017-05-05 15:09 UTC, jsmith2 approved these changes

2017-05-05 15:11 UTC, mhpnguyen approved these changes

2017-05-05 15:12 UTC, merged