FHAC-1462 added java.util.Locale and Locale.English
CONNECT-Solution/CONNECT pull request #1397
Opened 2017-05-08 19:12 UTC by ptambellini01

Added java.util.Locale import and Local.English to mitigate portability issues between different locales

2017-05-08 19:19 UTC, christophermay07 reviewed
Adding general feedback question regarding java.lang.String portability issues.

2017-05-08 19:19 UTC, christophermay07 commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/dashboard/DashboardViewResolverImpl.java
> +            if (panel.getType().replace(" ", "_").toLowerCase(Locale.ENGLISH).equals(id)) {
Why is .toLowerCase(Locale).equals(String) used instead of .equalsIgnoreCase(String)?

2017-05-08 19:29 UTC, mhpnguyen requested changes

2017-05-08 19:29 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/dashboard/DashboardViewResolverImpl.java
> +            if (panel.getType().replace(" ", "_").toLowerCase(Locale.ENGLISH).equals(id)) {
Why can't we use id.equalIgnoreCase check instead of the other way around? This option is more flexible than hard code English locale

2017-05-08 19:29 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/jee/jsf/UserAuthorizationListener.java
> +            return pageName.substring(1, pageName.length()).toLowerCase(Locale.ENGLISH);
Fortify only complain about comparing. We should stick to default toLowerCase and don't use "local.english".  We only need to check comparing by using equalIgnoreCase without using local.english. Check checkConfiguredDisplay() method and always to use "constant".equalIgnoreCase("stringtocompare")

2017-05-08 19:29 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/jee/jsf/UserAuthorizationListener.java
> +            return pageName.toLowerCase(Locale.ENGLISH);
Same comment as above.

2017-05-08 19:43 UTC, TabassumJafri requested changes
Please see my inline comment

2017-05-08 19:43 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/jee/jsf/UserAuthorizationListener.java
> +            return pageName.substring(1, pageName.length()).toLowerCase(Locale.ENGLISH);
Don't use toLowerCase(Locale.ENGLISH) here. Instead return the string and use equalsIgnoreCase comparison  in method checkConfiguredDisplay.

2017-05-08 19:46 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/dashboard/DashboardViewResolverImpl.java
> +            if (panel.getType().replace(" ", "_").toLowerCase().equalsIgnoreCase(id)) {
try to use id.equalsIgnoreCase(panel.getType().replace(" ", "_")) instead

2017-05-08 19:46 UTC, mhpnguyen requested changes
see my inline comments

2017-05-08 21:06 UTC, jsmith2 commented
Can you rename the commit?  Seems the changes requested have also caused a need for the commit message to be rewritten.

2017-05-08 21:08 UTC, jsmith2 commented
you might want to rebase and just get rid of the first two commits or just squash this into one commit.

2017-05-09 21:03 UTC, mhpnguyen approved these changes

2017-05-10 13:11 UTC, TabassumJafri approved these changes
Approved

2017-05-10 13:11 UTC, merged