added new tests for XDRPolicyTransformHelper.java
CONNECT-Solution/CONNECT pull request #1401
Opened 2017-05-09 13:41 UTC by balmeeki

Added new tests in XDRPolicyTransformHelperTest.java for ticket FHAC-1447

2017-05-09 18:19 UTC, mhpnguyen requested changes
Please follow our code format.

2017-05-09 18:19 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +//@RunWith(JMock.class)
remove it if we don't use

2017-05-09 18:19 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +	private static final String MESSAGE_ID = "12345566";
Please follow our code format.  I see a lot of tab instead of  space.

2017-05-09 18:19 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		XDREventType eventB = new XDREventType();
Do we need to declare object and then assign to null? Just remove them

2017-05-09 18:19 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		AssertionType assertionTypeTest = new AssertionType();
suggest to rename to assertionType instead of assertionTypeTest

2017-05-09 18:19 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		AssertionType assertionTypeTest = new AssertionType();
suggest to rename variable

2017-05-09 18:19 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		HomeCommunityType hct = new HomeCommunityType();
Duplicate block for set up test data.  consider to consolidate into 1 common set up.

2017-05-09 18:22 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		XDREventType eventB = new XDREventType();
these are separate null tests for code coverage... almost 10% of code is covered by these tests

2017-05-09 18:24 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +	private static final String MESSAGE_ID = "12345566";
this should be automatic... did same for adhocPolicyTest too

2017-05-09 18:25 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +//@RunWith(JMock.class)
removed

2017-05-09 18:26 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +	private static final String MESSAGE_ID = "12345566";
will remove tab

2017-05-09 18:32 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		XDREventType eventB = new XDREventType();
Following up on the comment from @mhpnguyen - is there any value in declaring eventA and eventB, as opposed to using the null directly?  e.g.,

`assertNull(xdrTransformHelper.transformXDRResponseToCheckPolicy(null));`

2017-05-09 18:33 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		XDREventType eventB = new XDREventType();
changed to
assertNull(xdrTransformHelper.transformXDRResponseToCheckPolicy(null));
		assertNull(xdrTransformHelper.transformXDRToCheckPolicy(null));

2017-05-09 18:35 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		AssertionType assertionTypeTest = new AssertionType();
done

2017-05-09 18:36 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +	private static final String MESSAGE_ID = "12345566";
done

2017-05-09 18:37 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +	private static final String MESSAGE_ID = "12345566";
This is according to code format

2017-05-10 14:22 UTC, TabassumJafri requested changes
Please see my inline comments

2017-05-10 14:22 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +
input parameter direction is not getting used anywhere in verifycheckPolicy_Request method.

2017-05-10 14:22 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		slotType1.setName("$XDSDocumentEntryPatientId");
Below lines are duplicated for both testTransformXDRResponseToCheckPolicy and
testTransformXDRToCheckPolicy. You can create a private method with SlotType  as return type and use it in both places.
slotType1.setName("$XDSDocumentEntryPatientId");  
 104   +  
 105   +		valueListType.getValue().add("1111.4444^^^&amp;26.489.22&amp;ISO");  
 106   +		slotType1.setValueList(valueListType);

2017-05-10 14:30 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +
yes... but you need to give direction as required parameter to run the tests

2017-05-10 14:31 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		slotType1.setName("$XDSDocumentEntryPatientId");
I want to keep it same manner... In AdhocQueryPolicyTest, was was done which Jason, Minh and you approved...

2017-05-10 14:38 UTC, balmeeki commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +
changing it

2017-05-10 15:37 UTC, TabassumJafri approved these changes

2017-05-10 15:37 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/transform/policy/XDRPolicyTransformHelperTest.java
> +		assertionType.setPersonName(pnt);
creation of assertionType is duplicated in both testTransformXDRResponseToCheckPolicy and
testTransformXDRToCheckPolicy. Try to do it in one place.

2017-05-10 16:00 UTC, mhpnguyen approved these changes

2017-05-10 16:00 UTC, merged