FHAC-1464- modified 4-High - XML External Entity Injection
CONNECT-Solution/CONNECT pull request #1403
Opened 2017-05-10 16:33 UTC by sjarral112

modified 4-High - XML External Entity Injection

XSLTransformHelper.java
ConnectionManagerDAOBase.java
CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/patientcorrelation/nhinc/config/ConfigurationManager.java
Product/Production/Services/DocumentSubmissionCore/src/main/java/gov/hhs/fha/nhinc/docsubmission/adapter/component/ConfigurationManager.java

2017-05-10 17:11 UTC, TabassumJafri requested changes
Please see my inline comments

2017-05-10 17:11 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +                DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
You are creating a DocumentBuilderFactory here and setting the features. However while marshaling you are not using DocumentBuilderFactory in any way. How setting the features will help marshaling in this case?

2017-05-10 17:15 UTC, mhpnguyen requested changes
Code format and consider to put all string value into NhincConstants.

2017-05-10 17:15 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/util/XSLTransformHelper.java
> +            tFactory.setFeature("http://xml.org/sax/features/external-general-entities", false);
Code format issue.

2017-05-10 17:15 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +                DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
Please verify the line number on the ticket.  The issue is on method loadBusinessDetail (line 54) not on saveBusinessDetail.  In additional to that, I don't see the benefit on new block that you introduce.  They are unused.

2017-05-12 15:31 UTC, mhpnguyen requested changes

2017-05-12 15:31 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +		} catch (ParserConfigurationException e) {
group all exception similar like this "catch (ParserConfigurationException | SAXException | FileNotFoundException e) "

2017-05-12 15:31 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +			LOG.error("unable to load XDRConfiguration file", e);
consider to use standard log LOG.error("custom message {}",e.getLocalizedMessage(),e);

2017-05-12 15:31 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +		try {
This probably code format issue since you don't modify anything in here.

2017-05-12 15:31 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/nhinclib/NhincConstants.java
> +	public static final String FEATURE_GENERAL_ENTITIES = "http://xml.org/sax/features/external-general-entities";
still see tab instead of space

2017-05-15 20:05 UTC, mhpnguyen approved these changes

2017-05-15 20:23 UTC, TabassumJafri approved these changes
approved without any further comments.

2017-05-15 20:23 UTC, merged