FHAC-1465: Add configurable TLS version in uddi service call
CONNECT-Solution/CONNECT pull request #1406
Opened 2017-05-17 14:03 UTC by mhpnguyen

- Add configurable TLS version in uddi service call only and won't affect nhinc gateway call.  If an customized entry doesn't exist gateway.propertiees, the uddi will uses jvm default option (JDK 7 uses TLSV1 while JDK8 uses TLSv1.2)
- Address some existing minor sonarqube violations.
@jsmith2 (optional)

2017-05-17 14:17 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSUddiClientEndpointDecorator.java
> + */
Missing CONNECT license clause.

2017-05-17 14:18 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSUddiClientEndpointDecorator.java
> +        HTTPConduit conduit = getHttpConduit();
Does this value need to be stored, or can it be used inline below (e.g., getHttpConduit().setTlsClientParameters(tlsCP))?

2017-05-17 14:23 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSClientParametersFactory.java
>      public static TLSClientParametersFactory getInstance() {
Consider using a Singleton pattern here.  For an example within the CONNECT codebase, see X12EntityExceptionBuilder.java.

2017-05-17 14:27 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSUddiClientEndpointDecorator.java
> +public class TLSUddiClientEndpointDecorator<T> extends TLSClientServiceEndpointDecorator<T> {
Within the CONNECT codebase, pick and choose whether acronyms will be camel-cased or not -- I strongly suggest not mixing and matching, e.g.:

Mixed (bad):  TLSUddi
Not mixed (okay):  TlsUddi
Not mixed (okay):  TLSUDDI

2017-05-17 14:39 UTC, TabassumJafri requested changes
Please see my inline comments

2017-05-17 14:39 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSClientParametersFactory.java
>              SSLSocketFactory factory = context.getSocketFactory();
there is no need to create context separately. You can use inline over here

2017-05-17 14:39 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSClientServiceEndpointDecorator.java
> +        HTTPConduit conduit = getHttpConduit();
Use inline method call over here.

2017-05-17 14:39 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSClientServiceEndpointDecorator.java
> +
remove these extra line spaces.

2017-05-17 14:39 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSUddiClientEndpointDecorator.java
> +            secureProtocol = StringUtils.replace(secureProtocol, ";", ",");
Is there a reason to store the values separated by semicolon

2017-05-17 14:39 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSClientParametersFactory.java
> +
extra line space

2017-05-17 18:40 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSUddiClientEndpointDecorator.java
> +            secureProtocol = StringUtils.replace(secureProtocol, ";", ",");
PropertyFileDAO and other places only allows ";".  To change this feature, we need to modify several places which are doable but they are outside of this scope.  We can create new ticket to track this issue

2017-05-17 18:42 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/messaging/service/decorator/cxf/TLSClientParametersFactory.java
>      public static TLSClientParametersFactory getInstance() {
Done. Convert this to follow Single Pattern.

2017-05-17 19:06 UTC, TabassumJafri approved these changes

2017-05-17 19:16 UTC, balmeeki approved these changes

2017-05-22 20:31 UTC, TabassumJafri approved these changes
Good with merge

2017-05-24 13:37 UTC, jsmith2 approved these changes

2017-05-24 16:57 UTC, merged