Redo 1454
CONNECT-Solution/CONNECT pull request #1410
Opened 2017-05-19 20:31 UTC by sjarral112

Did setFeature on xmlReader instead of SAX.

2017-05-19 20:34 UTC, balmeeki commented
approve to merge

2017-05-23 16:38 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +        } catch (final IOException e) {
Can these be made into a multicatch?

2017-05-23 19:03 UTC, mhpnguyen requested changes

2017-05-23 19:03 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +            LOG.error(NhincConstants.UNABLE_LOAD_XDR_FILE, e.getLocalizedMessage(), e);
We don't need to convert this exception msg into constant. Previously, sonarqube flag this since you don't have multiple catch and use the same msg.

2017-05-23 19:03 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/nhinclib/NhincConstants.java
> +        UDDI_SPEC_VERSION(String value) {
Revert this class

2017-05-23 19:03 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +                ByteArrayOutputStream out = new ByteArrayOutputStream();
Consider to close input/output stream

2017-05-23 20:19 UTC, mhpnguyen requested changes

2017-05-23 20:19 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +                reader.close();
what happen if exception happen before close statement?  recommend to move into final block

2017-05-24 17:16 UTC, christophermay07 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ConnectionManagerDAOBase.java
> +            writer.close();
Each close() should be in its own try/catch within the finally.  If reader.close() throws an Exception, writer.close() never gets called.

2017-05-24 20:13 UTC, TabassumJafri approved these changes
Good with merge

2017-05-24 20:13 UTC, mhpnguyen approved these changes
Endorse for merging

2017-05-24 20:15 UTC, merged