Disabled Document Retrieve redaction Engine Error testcases
CONNECT-Solution/CONNECT pull request #1413
Opened 2017-05-23 20:30 UTC by TabassumJafri

@mhpnguyen and @sovanncgi

2017-05-23 20:35 UTC, mhpnguyen requested changes
Consider to revert this file and only disable "<con:testCase" block

2017-05-23 20:35 UTC, mhpnguyen commented on Product/SoapUI_Test/RegressionSuite/Bimodal/AdapterRegistryErrorListMissingTest/AdapterRegistryErrorListMissingTest-soapui-project.xml
> +    <con:definitionCache type="TEXT" rootPart="file:/C:/CONNECT_Source/CONNECT/Product/SoapUI_Test/target/wsdl/EntityDocRetrieve.wsdl"><con:part><con:url>file:/C:/CONNECT_Source/CONNECT/Product/SoapU
Remove definitionCache block

2017-05-23 20:35 UTC, mhpnguyen commented on Product/SoapUI_Test/RegressionSuite/Bimodal/AdapterRegistryErrorListMissingTest/AdapterRegistryErrorListMissingTest-soapui-project.xml
> +    <con:definitionCache type="TEXT" rootPart="file:/C:/CONNECT_Source/CONNECT/Product/SoapUI_Test/RegressionSuite/target/wsdl/AdapterDocRetrieve.wsdl"><con:part><con:url>file:/C:/CONNECT_Source/CONN
Remove definitionCache  block

2017-05-24 12:52 UTC, TabassumJafri commented
Closing this PR because push contains the whole soap ui file and it is getting treated as a new file.

2017-05-24 12:52 UTC, closed without merging