Fhac 1530
CONNECT-Solution/CONNECT pull request #1433
Opened 2017-07-27 15:52 UTC by ptambellini01

2017-07-31 00:56 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            DateTime beginValidTime = new DateTime();
This doesn't allow for values to be passed in.  Should discuss the appropriate solution for this.

2017-08-03 13:28 UTC, mhpnguyen requested changes

2017-08-03 13:28 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            DateTime beginValidTime = new DateTime();
Move this initialization into the if block.  We only need them and create the assertion condition if we detect true value for this flag

2017-08-03 13:28 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            final String ConditionsDefaultValueEnabled = PropertyAccessor.getInstance()
Use java name convention. http://www.oracle.com/technetwork/java/codeconventions-135099.html

2017-08-03 13:28 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +                .getProperty(NhincConstants.GATEWAY_PROPERTY_FILE, NhincConstants.ENABLE_CONDITIONS_DEFAULT_VALUE);
Use getPropertyBoolean instead of getProperty.

2017-08-03 13:28 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            LOG.trace("Property not found exception: {}", pae.getLocalizedMessage(), pae);
Use one or the other.  Suggestion: Use trace since this is optional element

2017-08-03 13:28 UTC, mhpnguyen commented on Product/Production/Common/Properties/src/main/resources/gateway.properties
> +enableConditionsDefaultValue=true
Conditional is optional element. Should this become false?

2017-08-03 14:42 UTC, ptambellini01 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +                .getProperty(NhincConstants.GATEWAY_PROPERTY_FILE, NhincConstants.ENABLE_CONDITIONS_DEFAULT_VALUE);
The reason I used .getProperty was the AuthzDecisionConditions property was defined in the same way (See Below).
However, if I were to change one I should change the other.
    protected boolean isAuthDEvidenceConditionsDefaultValueEnabled() {
        // if not provided or invalid return true else false
        try {
            final String authDEvidenceConditionsDefaultValueEnabled = PropertyAccessor.getInstance().getProperty(
                NhincConstants.GATEWAY_PROPERTY_FILE, NhincConstants.ENABLE_AUTH_DEC_EVIDENCE_CONDITIONS_DEFAULT_VALUE);

2017-08-03 14:42 UTC, ptambellini01 commented on Product/Production/Common/Properties/src/main/resources/gateway.properties
> +enableConditionsDefaultValue=true
The other Conditions Value is set to true.
enableAuthDecEvidenceConditionsDefaultValue=true

2017-08-03 15:29 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            DateTime beginValidTime = new DateTime();
This whole new block should be moved into it's own method.

2017-08-03 15:40 UTC, jsmith2 commented on Product/Production/Common/Properties/src/main/resources/gateway.properties
> +enableConditionsDefaultValue=true
I would combine the two properties.  Should just be one property to evaluate conditions regardless of where the conditions is in the saml.

2017-08-03 15:42 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            DateTime beginValidTime = new DateTime();
I'm assuming this will be updated to include the new assertion values you're adding with common types?

2017-08-03 16:12 UTC, ptambellini01 commented on Product/Production/Common/Properties/src/main/resources/gateway.properties
> +enableConditionsDefaultValue=true
Just use the enableConditionsDefaultValue for both checks?

2017-08-04 19:33 UTC, jsmith2 requested changes

2017-08-04 19:33 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            if (isConditionsDefaultValueEnabled()) {
This isn't right.  Default enable only happens if the values passed in aren't valid.  Conditions should be created (value or not), if some sort of value is passed in via the assertion block.

2017-08-04 19:33 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +        beginValidTime = setBeginValidTime(beginValidTime, issueInstant);
This is where the  if statement should be for checking the property for allowing for corrected times.

2017-08-04 19:33 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CallbackMapProperties.java
> +    public DateTime getIssueInstant() {
How is issue instant populated?  Feel like this will always be null.  Not sure if this value is needed for this issue anyway.

2017-08-04 19:35 UTC, mhpnguyen requested changes

2017-08-04 19:35 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CallbackMapProperties.java
> +        return getNullSafeDateTime(SamlConstants.SAMLCONDITIONS_NOT_BEFORE_PROP, null);
Why do we retrieve SAMLCONDITIONS_NOT_BEFORE_PROP for issuestance?

2017-08-04 19:35 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/nhinclib/NhincConstants.java
>      public static final String ENABLE_AUTH_DEC_EVIDENCE_CONDITIONS_DEFAULT_VALUE = "enableAuthDecEvidenceConditionsDefaultValue";
consider to remove it if we consolidate

2017-08-04 19:35 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/saml/extraction/SamlTokenCreator.java
> +                    if (NullChecker.isNotNullish(assertion.getSamlConditions().getNotBefore())) {
Suggestion: Remove duplicate check for not null in assertion.getSamlConditions().getNotBefore().

2017-08-04 19:47 UTC, ptambellini01 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            if (isConditionsDefaultValueEnabled()) {
The isConditionsDefaultValueEnabled is defined in gateway properties.

2017-08-04 19:55 UTC, ptambellini01 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CallbackMapProperties.java
> +    public DateTime getIssueInstant() {
There was an issueInstant property defined for the Evidence Build that was used in for the Conditions element for AuthzDecisionStatement.

2017-08-15 15:48 UTC, mhpnguyen approved these changes

2017-08-15 16:40 UTC, TabassumJafri approved these changes
Approving without any comments

2017-08-15 17:09 UTC, merged