FHAC-1502: Check for emptiness issue for sonarqube
CONNECT-Solution/CONNECT pull request #1435
Opened 2017-07-31 14:12 UTC by trantang

Refactor code to use Collection instead of size.

2017-07-31 15:27 UTC, TabassumJafri requested changes
Please see my inline comments

2017-07-31 15:27 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/common/propaccessor/PropertyAccessHelper.java
>                  if (oInputProp.getPropertyName() == null || oInputProp.getPropertyName().length() <= 0) {
Could use a stringUtils.isEmpty check here.

2017-07-31 15:27 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/common/propaccessor/PropertyAccessHelper.java
>          if (part1 != null && part1.getPropertyFile() != null && part1.getPropertyFile().length() > 0) {
Need a StringUtils.isNotEmpty check here

2017-07-31 15:27 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/ConnectionManagerCache.java
>                          if (sHomeCommunityId != null && sHomeCommunityId.length() > 0) {
Could use StringUtils.isNotEmpty here

2017-07-31 15:27 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/transform/subdisc/HL7ArrayTransforms.java
> +                && !orig.getDevice().getAsAgent().getValue().getRepresentedOrganization().getValue().getId()
use CollectionUtils.isNotEmpty(orig.getDevice().getAsAgent().getValue().getRepresentedOrganization().getValue().getId())

2017-07-31 15:27 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/transform/subdisc/HL7Extractors.java
> +        if (CollectionUtils.isNotEmpty(names) && names.get(0).getContent() != null) {
Need a CollectionUtils.isNotEmpty check for names.get(0).getContent

2017-07-31 17:17 UTC, trantang commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/transform/subdisc/HL7Extractors.java
> +        if (CollectionUtils.isNotEmpty(names) && names.get(0).getContent() != null) {
"collection is not null" is not the same as "collection is not empty"

2017-07-31 18:03 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/transform/subdisc/HL7Extractors.java
> +        if (CollectionUtils.isNotEmpty(names) && names.get(0).getContent() != null) {
You are right Not null and empty checks on a collection are not same. However when we look at this method, getting an iterator and doing a while iterator.hasnext(), yields the same purpose as having an empty check in the if condition.

2017-07-31 19:06 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/transform/subdisc/HL7Extractors.java
> +        if (CollectionUtils.isNotEmpty(names) && names.get(0).getContent() != null) {
Had an offline discussion and I am ok to keep the code as is.

2017-08-01 15:02 UTC, TabassumJafri approved these changes

2017-08-01 19:11 UTC, mhpnguyen approved these changes

2017-08-01 19:23 UTC, ptambellini01 approved these changes

2017-08-02 13:38 UTC, merged