Fix chain of trust certification
CONNECT-Solution/CONNECT pull request #1436
Opened 2017-07-31 18:06 UTC by mhpnguyen

Apply special logic to handle chain of trust.  It will validate the passing cert against trust store to make sure  all the chain exist.
Optional: @trantang @ptambellini01

2017-07-31 19:04 UTC, TabassumJafri requested changes
Please see my inline comments

2017-07-31 19:04 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/callback/cxf/CertificateChainValidatorTest.java
> +        certManager = null;
remove commented out code

2017-07-31 19:04 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CertificateChainValidator.java
> +                certToCheck.getSerialNumber().toString(16));
You can use BASE16 constant .. using just 16 is very vague.

2017-07-31 19:04 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/callback/cxf/CertificateChainValidatorTest.java
> +        Assert.assertTrue("Our truststore should this chain of trust",certValidator.validateCert(certToCheck));
Need more meaningful message

2017-07-31 19:04 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +
Remove extra line spaces

2017-07-31 19:04 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CertificateChainValidator.java
> +        return false;// by default
remove the comments here .. add them as method level javadoc

2017-07-31 19:04 UTC, TabassumJafri commented on Product/Production/Common/Properties/src/main/resources/gateway.properties
> +ValiateChainOfTrust=false
Misspelled property

2017-08-01 13:26 UTC, jsmith2 commented on Product/Production/Common/Properties/src/main/resources/gateway.properties
> +ValiateChainOfTrust=false
Also misspelled validate.

2017-08-01 13:39 UTC, jsmith2 requested changes

2017-08-01 13:39 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +    private static final Logger LOG = LoggerFactory.getLogger(CONNECTSamlAssertionValidator.class);
Change this back to to log4j.  I don't think the SLF4J change was made during 4.5.

2017-08-01 13:39 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/CONNECTSamlAssertionValidator.java
> +            return propertyAccessor.getPropertyBoolean(NhincConstants.GATEWAY_PROPERTY_FILE, "ValiateChainOfTrust");
Validate spelled wrong. "ValidateChainOfTrust"

2017-08-01 17:16 UTC, TabassumJafri approved these changes
Endorsing for merge

2017-08-01 18:08 UTC, jsmith2 approved these changes

2017-08-01 18:14 UTC, merged