CONN-1758 Decision is always Permit
CONNECT-Solution/CONNECT pull request #1441
Opened 2017-08-18 13:08 UTC by trantang

removed the code that allow user to change the Decision
Decision Element is not removed; this created a chain of unwanted code change

2017-08-18 13:48 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            String decision = AUTHZ_DECISION_PERMIT;
Unneeded local variable, just put the constant value into the method a couple lines below.

2017-08-18 13:51 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            String decision = AUTHZ_DECISION_PERMIT;
Also, remove the comment.  I don't think it's needed.

2017-08-21 13:03 UTC, TabassumJafri requested changes
Please see inline comments

2017-08-21 13:03 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
>              final Evidence evidence = createEvidence(properties, subject);
Remove the isValidAuthorizationDecision and AUTHZ_DECISION_DENY method in SAMLAssertionbuilder as well.

2017-08-21 17:27 UTC, TabassumJafri approved these changes
good with merge

2017-08-21 17:42 UTC, mhpnguyen approved these changes

2017-08-21 17:42 UTC, merged