CONN-1751 conditions optional
CONNECT-Solution/CONNECT pull request #1442
Opened 2017-08-21 18:41 UTC by trantang

Update authz decision statement conditions to be optional and do not need processing

2017-08-21 19:44 UTC, TabassumJafri commented
Not specific to this PR however I see there are some constants present in both SAMLConstants and NhincConstants. Can we port all saml related constants in SAMLConstants? For instance, we have these 2 values defined in both classes:
   String EVIDENCE_CONDITION_NOT_BEFORE_PROP = "evidenceConditionNotBefore";
   String EVIDENCE_CONDITION_NOT_AFTER_PROP = "evidenceConditionNotAfter";

2017-08-21 19:44 UTC, TabassumJafri requested changes

2017-08-21 19:44 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilderTest.java
> +        assertNull(conditions);
We are just asserting on null here. Could we have some more meaningful values to test for?

2017-08-21 19:57 UTC, trantang commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilderTest.java
> +        assertNull(conditions);
based on the given the values, the conditions is null

2017-08-22 14:32 UTC, TabassumJafri approved these changes

2017-08-22 14:55 UTC, ptambellini01 approved these changes

2017-08-22 14:57 UTC, merged