Conn 1736
CONNECT-Solution/CONNECT pull request #1444
Opened 2017-08-22 00:31 UTC by jsmith2

Minor updates for finishing conditions statements (unit test and usage of property)

2017-08-22 14:14 UTC, TabassumJafri requested changes

2017-08-22 14:14 UTC, TabassumJafri commented on Product/Production/Common/Properties/src/main/resources/gateway.properties
>  enableConditionsDefaultValue=true
need to remove the property enableAuthDecEvidenceConditionsDefaultValue from NhincConstants.java

2017-08-22 14:14 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            if(beginValidTime.isBefore(endValidTime)) {
Do we need to error out if beginValidTime.isBefore(endValidTime) not met?

2017-08-23 15:00 UTC, TabassumJafri approved these changes

2017-08-23 15:47 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            if (isConditionsDefaultValueEnabled() || beginValidTime.isAfter(endValidTime)) {
Optional: Duplication logic. Consider to use createCondition method since

2017-08-23 16:30 UTC, ptambellini01 approved these changes

2017-08-23 17:12 UTC, merged