CONN-1759 ACP/IACP AuthzDecisionStatement
CONNECT-Solution/CONNECT pull request #1445
Opened 2017-08-22 17:18 UTC by trantang

One of the ACP or IACP is required in the AuthzDecisionStatement; if none exist AuthzDecisionStatement is invalid and should not be created.

2017-08-22 19:46 UTC, ptambellini01 requested changes
In the HOKSamlAssertionBuilder, there are only one condition being tested, whether or not there are two conditions ACP/IACP or not. Shouldn't it at least have one other test. Whether it fails to write if there aren't at least one condition.

2017-08-22 20:35 UTC, TabassumJafri requested changes
Please see my inline comments

2017-08-22 20:35 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +        if (CollectionUtils.isEmpty(accessConstentValues)) {
These 2 if conditions and log statements are unnecessary. We can rew3ord and write these log statement in OpenSaml2Builder.createEvidenceStatements method.

2017-08-22 20:35 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/OpenSAML2ComponentBuilder.java
>              attributes.add(createAttribute(null, NhincConstants.ACCESS_CONSENT_ATTR, namespace, accessConstentValues));
ACCESS_CONSENT_ATTR and INST_ACCESS_CONSENT_ATTR are defined in both SamlConstants and NhincConstants. Remove from NhincConstants.

2017-08-23 18:53 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +    public static List<Object> checkPrefixInList(final List<Object> valueList, final String checkPrefix){
These two methods can be combined.   No need to create a whole new method just to pass in a constant.

2017-08-24 17:39 UTC, ptambellini01 approved these changes

2017-08-24 19:41 UTC, mhpnguyen approved these changes

2017-08-25 15:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +        if(CollectionUtils.isEmpty(accessConstentValues) && CollectionUtils.isEmpty(evidenceInstanceAccessConsentValues)){
This should have popped up on sonarqube.  Can be simplified to:

return !Collections.IsEmpty(accessConsentValues) && !CollectionUtils.isEmpty(evidenceInstanceAccessConsentValues);

No need for if statement.

2017-08-25 17:05 UTC, jsmith2 approved these changes

2017-08-25 17:08 UTC, merged