CONN-1768-add capability to pass all subject confirmation method
CONNECT-Solution/CONNECT pull request #1459
Opened 2017-09-11 13:54 UTC by mhpnguyen

Include a new feature to pass all subject confirmation method (sender-vouches/bear) from nhinc layer to adapter.
@trantang (Optional), @pvenkatakrishnan1 (Optional)

2017-09-11 17:56 UTC, TabassumJafri requested changes

2017-09-11 17:56 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/saml/extraction/SamlTokenCreator.java
> +        LOG.debug("Entering SamlTokenCreator.CreateRequestContext... version 1234");
Not sure what's the purpose of version 1234

2017-09-11 17:56 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/saml/extraction/SamlTokenCreator.java
> +                bean.setNotBefore(dateFormat.parseDateTime(subjectCondition.getNotBefore()));
Check for null for both getNotOnOrAfter and getNotBefore before parsing

2017-09-12 12:54 UTC, TabassumJafri approved these changes

2017-09-12 15:25 UTC, jsmith2 approved these changes

2017-09-12 15:25 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/saml/extraction/SamlTokenCreator.java
> +        LOG.debug("Entering SamlTokenCreator.CreateRequestContext... version 1234");
Remove version 1234.

2017-09-12 15:25 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/saml/extraction/SamlTokenCreator.java
> +        LOG.debug("Entering SamlTokenCreator.CreateRequestContext... version 1234");
Also, change this logging level to trace.

2017-09-12 15:25 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/saml/extraction/SamlTokenCreator.java
> +                bean.setNotAfter(dateFormat.parseDateTime(subjectCondition.getNotOnOrAfter()));
should we validate the dates or have the option to using the same property that we have for the other notbefore/notAfter values?

2017-09-12 15:25 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +                subject.getSubjectConfirmations().add(bearConfirmation);
Same variable names (change to senderVouches.

2017-09-12 15:25 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilderTest.java
> +                // TODO Auto-generated method stub
get rid of TODOs.

2017-09-12 15:26 UTC, merged