Conn 1847 sub
CONNECT-Solution/CONNECT pull request #1470
Opened 2017-09-18 20:01 UTC by pvenkatakrishnan1

CONN-1847 SonarQube violations- Source files should not have any duplicated blocks

2017-09-18 21:01 UTC, trantang requested changes
please reviewed all the logging methods and add missing log parameters;  i also recommend adding seperator between the log's Text and Log's parameter

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7DbParser201305.java
> +                            LOG.info("nameString{}", nameString);
when you used parameter in the log add a separator for readability "nameString: {}"

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7DbParser201305.java
> +            LOG.info("setting name by nameString ", nameString);
you forgot a parameter in the logging here: "setting name by nameString {}"

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7DbParser201305.java
> +            LOG.info("FamilyName : ", personNameDBModel.getLastName());
need log parameter in your string

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7DbParser201305.java
> +                                    LOG.info("found addressLine1 element; content{}", addressLine1.getContent());
separate your log parameter and the text

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7DbParser201305.java
> +                                + "][id=" + ssnId.getId() + "]");
use multiple log parameters for the logging
LOG.info("Created id from ssn identifier [organization: {} ][id: {} ]", 
ssnId.getOrganizationId(), ssnId.getId());

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7Parser201305.java
> +                            + id.getId() + "]");
used multiple log's parameters here

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7Parser201305.java
> +                            LOG.info("found city element; content=", city.getContent());
missing log parameter

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7Parser201305.java
> +                            LOG.info("found state element; content=", state.getContent());
missing log parameter

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdb/dao/PatientDAO.java
> +            LOG.trace("DAO-getAll-patients-count: " + patients.size());
missing log's parameter

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdiscovery/adapter/proxy/AdapterPatientDiscoveryProxyWebServiceHelper.java
> +                LOG.debug("After target system URL look up. URL for service{} ", sServiceName, "and url= ", url);
recommend
LOG.debug("After target system URL look up. URL for service: {} and url: {} ", sServiceName, url);

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdiscovery/entity/proxy/EntityPatientDiscoveryProxyWebServicAbstract.java
> +                "Error getting url for " + serviceName + " from the connection manager. Error: " + ex.getMessage(), ex);
use log's parameter here

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdiscovery/entity/proxy/EntityPatientDiscoveryProxyWebServiceSecuredImpl.java
>              LOG.error("Error calling respondingGatewayPRPAIN201305UV02: " + ex.getMessage(), ex);
missing log's parameter

2017-09-18 21:01 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdiscovery/entity/proxy/EntityPatientDiscoveryProxyWebServiceUnsecuredImpl.java
>              LOG.error("Error calling respondingGatewayPRPAIN201305UV02: " + ex.getMessage(), ex);
missing log parameter

2017-09-19 12:08 UTC, TabassumJafri requested changes

2017-09-19 12:08 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7DbParser201305.java
> +                if (telecom != null) {
use StringUtils.isNotEmpty check here

2017-09-19 12:08 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/mpi/adapter/component/hl7parsers/HL7Parser201305.java
>                      && subjectId.getRoot() != null && subjectId.getRoot().length() > 0) {
Can we use StingUtils here instead of checking null and length

2017-09-19 12:08 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdb/dao/AddressDAO.java
>          boolean result = true;
There is no need for declaring result variable. You can simply do return super.create

2017-09-19 12:08 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdb/dao/AddressDAO.java
> +            result = super.update(addressRecord);
No need for declaring result here

2017-09-19 12:08 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdb/dao/IdentifierDAO.java
>          boolean result = true;
No need to declare result here

2017-09-19 12:08 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdb/dao/PersonnameDAO.java
>          boolean result = true;
No need for result variable

2017-09-19 12:08 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdiscovery/PatientDiscovery201305Processor.java
> +                LOG.error(ex.getMessage(), ex);
Use parameterized logging here

2017-09-19 12:58 UTC, pvenkatakrishnan1 commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdb/dao/AddressDAO.java
>          boolean result = true;
I guess the local variable result will help for null check in the entity object being passed.

2017-09-19 15:19 UTC, TabassumJafri approved these changes

2017-09-19 15:30 UTC, trantang requested changes

2017-09-19 15:30 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdiscovery/PatientDiscovery201305Processor.java
> +        LOG.debug("Begin storeLocalMapping: hcid", hcid);
missing log's parameter

2017-09-19 15:30 UTC, trantang commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdiscovery/adapter/proxy/AdapterPatientDiscoveryProxyWebServiceHelper.java
> +                LOG.debug("After target system URL look up. URL for service: {} ", sServiceName, "and url : {}  ", url);
LOG.debug("After target system URL look up. URL for service: {} and url : {}  ", sServiceName, url);

combine the messages and separate the parameters

2017-09-19 16:02 UTC, trantang approved these changes
Approved.

2017-09-19 16:02 UTC, merged