CONN-1903 Certificate Manager GUI updates
CONNECT-Solution/CONNECT pull request #1491
Opened 2017-10-19 18:36 UTC by pvenkatakrishnan1

2017-10-19 19:23 UTC, mhpnguyen requested changes

2017-10-19 19:23 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/event/model/Certificate.java
> +                setExpiryColorCoding("RED");
Consider to use enum instead of constant string

2017-10-19 19:23 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/event/model/Certificate.java
> +            Date CertExpiryDate = x509Cert.getNotAfter();
Use java "CamelCase" for name like Date certExpiredDate

2017-10-19 19:23 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/event/model/Certificate.java
> +                // HelperUtil.addMessageError(IMPORT_CERT_ERR_MSG, "This Certificate is expiring soon");
remove this comment

2017-10-19 19:23 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/event/model/Certificate.java
> +                setExpiryColorCoding("RED");
Try to use enum instead of constant.  Our enum defines under GUIConstants.java

2017-10-19 19:23 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +                // HelperUtil.addMessageError(IMPORT_CERT_ERR_MSG, "This Certificate is expiring soon");
remove this comment

2017-10-19 19:23 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +            Date today = new Date();
Duplicate logic to get number of expired date in Certificate.java

2017-10-19 19:23 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +                    new FacesMessage(FacesMessage.SEVERITY_INFO, "INFO", "This Certificate is expiring soon."));
Try to reuse our static method in HelperUtil.addMessageInfo() method

2017-10-20 13:46 UTC, TabassumJafri requested changes

2017-10-20 13:46 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/event/model/Certificate.java
> +            // Tue Oct 17 06:02:22 AEST 2006
Remove comments

2017-10-20 13:56 UTC, TabassumJafri approved these changes

2017-10-20 14:02 UTC, mhpnguyen approved these changes

2017-10-20 14:02 UTC, merged