Transformed UDDI objects to FHIR schema
CONNECT-Solution/CONNECT pull request #1496
Opened 2017-10-24 13:33 UTC by TabassumJafri

2017-10-24 16:10 UTC, mhpnguyen requested changes

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/ConnectionManagerCache.java
> +            BusinessDetail bDetail = this.getUddiConnectionManagerDAO().loadBusinessDetail();
We should not call loadBusinessDetail twice since we already did in loadUDDIConnectionInfo().  Maybe pass BusinessDetail as argument into this method

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/ConnectionManagerCache.java
> +        if (exList != null && CollectionUtils.isNotEmpty(exList)) {
remove null check since CollectionUtils already did that

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ExchangeInfoDAOFileImpl.java
> +        LOG.debug("Reading exchangeInfo from file: " + fileName);
Use parameterized logging

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ExchangeInfoDAOFileImpl.java
> +            if (sValue != null && sValue.length() > 0) {
Optional: use stringUtil class to null and value string

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ExchangeInfoDAOFileImpl.java
> +            throw new ConnectionManagerException("Unable to save to Connection Information File " + file.getName(), ex);
Use parameterized logging

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchange/transform/uddi/UDDITransform.java
> +    public static final String UDDI_SPEC_VERSION_KEY = "uddi:nhin:versionofservice";
If possible, can we consolidate those constant variable into another class? I saw we have multiple constant in separate classes

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchange/transform/uddi/UDDITransform.java
> +        if (entity.getIdentifierBag() != null && CollectionUtils.isNotEmpty(entity.getIdentifierBag().
No need to check for null if using Collectionutils.isnotempty

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchange/transform/uddi/UDDITransform.java
> +                if (key.getTModelKey().equals(UDDI_HOME_COMMUNITY_ID_KEY)) {
Use reverse equals to prevent NPE

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchange/transform/uddi/UDDITransform.java
> +        if (null != entity.getBusinessServices() && CollectionUtils.isNotEmpty(entity.getBusinessServices().
No need to check for null if using CollectionUtils method

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchange/transform/uddi/UDDITransform.java
> +                if (null != keyRef.getTModelKey() && keyRef.getTModelKey().equalsIgnoreCase(UDDI_STATE_KEY)) {
remove null check here and use reverse check "constant.equalsignorecases(variable)"

2017-10-24 16:10 UTC, mhpnguyen commented on Product/Production/Common/Properties/src/main/resources/exchangeInfo.xml
> +    <lastUpdated></lastUpdated>
Optional: We need to migrate all constant variable in gateway.properties that relate to Uddi and mapping into this xml

2017-10-24 17:03 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/ExchangeInfoDAOFileImpl.java
> +            throw new ConnectionManagerException("Unable to save to Connection Information File " + file.getName(), ex);
I am creating a string to pass to ConnectionManagerException.  Cannot use parameterized logging here

2017-10-24 17:03 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchange/transform/uddi/UDDITransform.java
> +        if (entity.getIdentifierBag() != null && CollectionUtils.isNotEmpty(entity.getIdentifierBag().
These check are on two different objects. Null check is on entity.getIdentifierBag() and CollectionUtils.isNotEmpty check is on entity.getIdentifierBag(). getKeyedReference()

2017-10-24 17:03 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchange/transform/uddi/UDDITransform.java
> +        if (null != entity.getBusinessServices() && CollectionUtils.isNotEmpty(entity.getBusinessServices().
These are 2 different objects and null check is on entity.getBusinessServices()

2017-10-24 18:52 UTC, jsmith2 requested changes

2017-10-24 18:52 UTC, jsmith2 commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/ConnectionManagerCache.java
> +                if (type.equalsIgnoreCase(ex.getType())) {
I don't think you should be removing by type, but rather by exchange name.  You could potentially have two exchanges that you work with that both use UDDI or FHIR, etc.

2017-10-25 14:44 UTC, mhpnguyen approved these changes

2017-10-25 14:44 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchange/transform/uddi/UDDITransform.java
> +        if (entity.getIdentifierBag() != null && CollectionUtils.isNotEmpty(entity.getIdentifierBag().
Agree. ignore my comments

2017-10-25 14:46 UTC, jsmith2 approved these changes

2017-10-25 14:47 UTC, merged