New exchange schema integration
CONNECT-Solution/CONNECT pull request #1511
Opened 2017-11-08 21:17 UTC by TabassumJafri

2017-11-09 15:50 UTC, trantang commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/connectmgr/uddi/UDDIUpdateManagerHelper.java
>              LOG.error("Error refreshing UDDI: {}", sErrorMessage, e);
should this merged into one string?

LOG.error("Error refreshing UDDI: Failed to retrieve data from UDDI.  Error: {}", e.getLocalizedMessage(), e);

2017-11-09 15:54 UTC, trantang commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/SchedulerKickOff.java
> +            LOG.error("Unable to start ExcahngeScheduler {}", ex.getLocalizedMessage(), ex);
spelling: ExcahngeScheduler

2017-11-09 15:59 UTC, mhpnguyen requested changes

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/SchedulerKickOff.java
> +    public SchedulerKickOff() {
Do we need to have default constructor? If not, remove it

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/SchedulerKickOff.java
> +public class SchedulerKickOff {
Optional: can we rename this class to something more meaningful (like ExchangeUpdateScheduler)?

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/SchedulerKickOff.java
> +            LOG.error("Unable to start ExcahngeScheduler {}", ex.getLocalizedMessage(), ex);
Misspelling ExcahngeScheduler

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduler.java
> +    protected ExchangeScheduler() {
Can this default constructor remove?

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduler.java
> +                refreshInterval = DEFAULT_EXCHANGE_REFRESH_INTERVAL * MINUTES_TO_MILLIS;
Optional: Use this calculation to convert day to milisecond: TimeUnit.MILLISECONDS.convert(1, TimeUnit.DAYS) or TimeUnit.DAYS.toMillis(1);

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduler.java
> +                refreshInterval = interval * MINUTES_TO_MILLIS;
Optional: Use this calculation: TimeUnit.MINUTES.toMillis(1)

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduler.java
> +    public void stopTimer() {
Since I don't see that we call stopTimer(), should we call this method inside destroy-method for applicationcontext.xml?

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduler.java
> +            LOG.error(sErrorMessage, e);
No need to log again since you already wrap e exception into ExchangeScheduleException.

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduler.java
> +                Thread.sleep(refreshInterval);
Optional: For debug purpose, should we include log.info to display refreshInterval?

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduledTask.java
> +                        && StringUtils.isNotEmpty(ex.getUrl())) {
For debug purpose, can we at least put log.info to display ex.getUrl so that we know what url that we try to hit

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduledTask.java
> +    private XMLGregorianCalendar getTimestamp() throws DatatypeConfigurationException {
Duplicate code inside XMLDateUtil.long2Gregorian()

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduledTask.java
> +        int noOfBackups = (null != maxNumBackup ? maxNumBackup.intValue() : 0);
No need to check in here since maxNumBackup value will always > 0 based on the caller logic

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/connectmgr/uddi/UDDIUpdateManagerHelper.java
> +        UDDIUpdateManagerForceRefreshRequestType part1) {
I think this method is no longer applicable.  Try to remove it along with UDDIUpdateManager.java

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/connectmgr/uddi/UDDIUpdateManager.java
> +        gov.hhs.fha.nhinc.common.connectionmanagerinfo.UDDIUpdateManagerForceRefreshRequestType uddiUpdateManagerForceRefreshRequest) {
I don't think we ever use this method again

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduledTask.java
> +                LOG.warn("Failed to delete backup file {}: {}", filenameToDelete, e.getLocalizedMessage());
Can we use only 1 log level? like warn

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/connectmgr/uddi/UDDITimerTask.java
> +         * try { UDDIUpdateManagerHelper helper = new UDDIUpdateManagerHelper(); helper.forceRefreshUDDIFile(); } catch
Remove it

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/connectmgr/uddi/UDDITimerTask.java
>          boolean bUDDIActive;
Do we still need method anymore?  remove it if we don't.  Make sure we also remove uddi related in gateway.properties

2017-11-09 15:59 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/connectmgr/persistance/dao/InternalExchangeInfoDAOFileImpl.java
> +public final class InternalExchangeInfoDAOFileImpl extends AbstractConnectionManagerDAO<ExchangeInfoType> {
This class contains a lot of duplicate code from external exchange

2017-11-09 16:31 UTC, jsmith2 requested changes
Needs update for change of variable name from "targetUrl" to "exchangeUrl"  and a couple other minor suggestions.   Very nice work.

2017-11-09 16:31 UTC, jsmith2 commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/connectmgr/uddi/UDDITimerTask.java
>      }
Are we leaving this commented out code here for now for a reason?  Should there be a TODO here?

2017-11-09 16:31 UTC, jsmith2 commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/connectmgr/uddi/UDDIUpdateManager.java
> +        LOG.info("forceRefreshFileFromUDDIServer");
The log should be trace level.

2017-11-09 16:31 UTC, jsmith2 commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduledTask.java
> +                    }
Should you put a TODO here as a reminder that this is where the FHIR update will be called too?

2017-11-09 16:34 UTC, trantang approved these changes

2017-11-09 19:17 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/connectmgr/uddi/UDDIUpdateManager.java
> +        gov.hhs.fha.nhinc.common.connectionmanagerinfo.UDDIUpdateManagerForceRefreshRequestType uddiUpdateManagerForceRefreshRequest) {
This method is used by the NhinComponenetConnectionManager service. We can revisit the removal of this service including xsd, wsdl, soapui test and java code in a separate ticket.

2017-11-09 20:00 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCommonWeb/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeScheduler.java
> +    public void stopTimer() {
stopTimer is now called in the destroy method of ExchangeUpdateScheduler

2017-11-09 20:35 UTC, mhpnguyen approved these changes

2017-11-13 17:51 UTC, jsmith2 approved these changes

2017-11-13 17:51 UTC, merged