CONN-1939 Update password handling in the Certificate Manager
CONNECT-Solution/CONNECT pull request #1524
Opened 2017-11-28 18:46 UTC by pvenkatakrishnan1

2017-11-28 20:02 UTC, mhpnguyen requested changes

2017-11-28 20:02 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/hibernate/LoginServiceImpl.java
> +import gov.hhs.fha.nhinc.devtools.admingui.services.PasswordService;
don't use devtool package

2017-11-28 20:02 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/services/impl/CertificateManagerServiceImpl.java
> +    private String getTrustStorePassKey() {
use user enter system password

2017-11-28 20:02 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/services/impl/CertificateManagerServiceImpl.java
> +            configUser.setUserName(user.getSalt());
revert back to user.getUserName

2017-11-28 20:15 UTC, TabassumJafri requested changes

2017-11-28 20:15 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/services/impl/CertificateManagerServiceImpl.java
> +        ConfigAssertionType assertion = buildConfigAssertion(getKeyStorePassKey());
No need for password/hash for listKeystore/listTrustStore

2017-12-01 15:25 UTC, TabassumJafri requested changes

2017-12-01 15:25 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/services/impl/CertificateManagerServiceImpl.java
> +                "UTF-8");
Use constant here

2017-12-01 17:49 UTC, mhpnguyen commented
test this please

2017-12-01 18:50 UTC, mhpnguyen commented
add to whitelist

2017-12-01 21:02 UTC, mhpnguyen requested changes
remove all

2017-12-01 21:02 UTC, mhpnguyen commented on Product/Production/Gateway/CONNECTGatewayWeb/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdminUnsecured.java
> +    private static final String INVALID_USER = "Invalid user credentials";
It is more about mismatch token.  Maybe the error should be "Mismatch Hash Token'

2017-12-01 21:02 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +        return StringUtils.isBlank(getHashTokenFromSession()) ? true : false;
remove "?true:false". It is unnecessary

2017-12-01 21:02 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +            if (service.validateTrustStorePassKey(trustStorePasskey)) {
we should not validate the hashtoken on client since we don't know the system password.

2017-12-01 21:02 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +            if (service.validateTrustStorePassKey(trustStorePasskey)) {
similar issue here. remove validation in client

2017-12-01 21:02 UTC, mhpnguyen commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +            if (service.validateTrustStorePassKey(trustStorePasskey)) {
remove validation on client

2017-12-04 18:53 UTC, mhpnguyen commented
test this please

2017-12-04 19:21 UTC, TabassumJafri approved these changes

2017-12-04 19:36 UTC, mhpnguyen approved these changes

2017-12-04 19:37 UTC, merged