Conn 1909 ver2 New GUI updates for Admin GUI Test Data Loader
CONNECT-Solution/CONNECT pull request #1526
Opened 2017-11-29 19:01 UTC by ptambellini01

2017-11-29 19:15 UTC, trantang requested changes

2017-11-29 19:15 UTC, trantang commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/LoadTestDataDocumentBean.java
> +        return HelperUtil.getMsgWarn(MessageFormat.format("Select a {0} for delete.", ofType.toLowerCase()));
I think we decide to put the "a" or "an" in the constant it can be removed for the message-text

2017-11-29 19:15 UTC, trantang commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/LoadTestDataDocumentBean.java
> +        return HelperUtil.getMsgWarn(MessageFormat.format("Select a {0} for edit.", ofType.toLowerCase()));
I think we decide to put the "a" or "an" in the constant it can be removed for the message-text

2017-11-29 20:20 UTC, pvenkatakrishnan1 requested changes
Some QA issues are not fixed.

2017-11-30 18:46 UTC, pvenkatakrishnan1 approved these changes
Looks good.

2017-11-30 18:46 UTC, trantang approved these changes

2017-11-30 18:47 UTC, merged