added code to remove defaultExchange
CONNECT-Solution/CONNECT pull request #1587
Opened 2018-01-25 17:45 UTC by TabassumJafri

added code to remove defaultExchange  when user deletes an Exchange on AdminGUI

2018-01-25 19:54 UTC, trantang requested changes

2018-01-25 19:54 UTC, trantang commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeManager.java
> +        return exInfo.getDefaultExchange();
need null-checked here

2018-01-25 19:54 UTC, trantang commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeManager.java
> +            map = exCache.get(exInfo.getDefaultExchange());
used the getDefaultExchange() and not the exInfo.getDefaultExchange()

2018-01-25 23:35 UTC, trantang approved these changes

2018-01-26 02:44 UTC, pvenkatakrishnan1 approved these changes

2018-01-26 02:44 UTC, merged