CONN-2139 Test Data Document Correction
CONNECT-Solution/CONNECT pull request #1629
Opened 2018-04-04 20:27 UTC by ptambellini01

2018-04-05 14:04 UTC, TabassumJafri requested changes

2018-04-05 14:04 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/services/LoadTestDataDBServiceImpl.java
> +            for (int i = 0; i < delDocument.size(); i++) {
What happens if a patient is deleted however you get an exception while deleting a document? I think this whole process, that is deleting a patient and associated documents, should be one transaction.

2018-04-09 12:37 UTC, plobre approved these changes

2018-04-09 13:25 UTC, TabassumJafri approved these changes

2018-04-09 13:25 UTC, merged