fix PD secure and unsecure to use correct CONNECT Client factory
CONNECT-Solution/CONNECT pull request #1630
Opened 2018-04-06 21:06 UTC by mhpnguyen

Fix PD adapter to use correct service regarding secure and unsecure.

2018-04-06 22:02 UTC, jsmith2 requested changes

2018-04-06 22:02 UTC, jsmith2 commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientdiscovery/adapter/proxy/AdapterPatientDiscoveryProxyWebServiceHelper.java
> +                    if (NhincConstants.ADAPTER_PATIENT_DISCOVERY_SECURED_SERVICE_NAME.equals(sServiceName)) {
Suggestion, pull out the added logic into a new method:  buildPortDescriptor(String sServiceName), that will pull out the added if/else statement.  Also rename this helper method.  Should be something like sendToPRPAIN201306UV02Adapter(...).  The current name "formatGatewayResponsePRPAIN201305UV02" isn't really what it does.  There is no formatting.

2018-04-07 01:03 UTC, TabassumJafri reviewed
Reviewed and will approve once the review comments are addressed

2018-04-09 12:27 UTC, TabassumJafri approved these changes

2018-04-09 14:07 UTC, jsmith2 approved these changes

2018-04-09 14:10 UTC, merged