CONN_2144: Adding required attributes to be checked during CXF callba…
CONNECT-Solution/CONNECT pull request #1642
Opened 2018-04-24 17:01 UTC by plobre

Adding required attributes to be checked during CXF callback. Will now throw a 
SAMLAssertionBuilderException if any of the required fields are null or blank.

Refactored quite a bit of the Unit Test to avoid creating its own classes for the sake of the test. We have Mockito, and a setter to set the CallbackProperties. There is absolutely no need to override the classes methods.

Removed a number of useless/incorrect comments in the code that were not needed.

2018-04-24 19:35 UTC, TabassumJafri requested changes

2018-04-24 19:35 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +        attributes.add(componentBuilder.createUserRoleAttribute(userCode, userSystem, userSystemName, userDisplay));
Can this be changed to createSubjectRoleAttribute?

2018-04-24 19:35 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            Attribute attribute = componentBuilder.createPatientIDAttribute(patientId);
rename the method to createResourceIdAttributeStatements

2018-04-24 19:39 UTC, plobre commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +        attributes.add(componentBuilder.createUserRoleAttribute(userCode, userSystem, userSystemName, userDisplay));
Absolutely! I'll change this one and `createPatientIDAttribute`

2018-04-26 14:33 UTC, TabassumJafri requested changes

2018-04-26 14:33 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/HOKSAMLAssertionBuilder.java
> +            LOG.error("No information provided to fill in user role attribute..");
Update Log and exception message to state Subject Role instead of user Role

2018-04-26 15:14 UTC, TabassumJafri approved these changes

2018-04-26 15:16 UTC, trantang approved these changes

2018-04-26 15:18 UTC, ptambellini01 approved these changes

2018-04-26 15:19 UTC, merged