Conn 2167 - Adding Skeleton Document Data Submission
CONNECT-Solution/CONNECT pull request #1657
Opened 2018-05-18 14:42 UTC by plobre

Adds and binds a skeleton Document Data Submission SOAP service with the appropriate Standard/Passthrough bean wiring. Also adds a skeleton adapter for reference.

These classes will be implemented in a later story.

2018-05-18 14:53 UTC, plobre commented
Note: This story depends on https://github.com/CONNECT-Solution/CONNECT-Webservices/pull/42 as there were changes to the WSDL. PR validator will not pass until that is merged first.

2018-05-18 19:15 UTC, mhpnguyen commented
retest this please

2018-05-18 20:34 UTC, TabassumJafri requested changes
Update internalExchangeInfo.xml and exchangeInfo in Properties folder only.

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Adapters/DocumentDataSubmission_a0/src/main/webapp/WEB-INF/cxf-servlet.xml
> +			<entry key="mtom-enabled" value="true" />
Not sure we need MTOM support for DDS

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/test/resources/exchangeInfo.xml
> +					<ns2:name>DOD</ns2:name>
Need DDS endpoint for organization urn:oid:1.1 as well

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/test/resources/exchangeInfo.xml
> +							<ns2:name>DocumentDataSubmissionService</ns2:name>
I would say name this as DocumentDataSubmission. The ehealthExchange directory will probably have DocumentDataSubmission.

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/test/resources/internalExchangeInfo.xml
> +									<ns2:version>LEVEL_a0</ns2
It needs to be https

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/test/resources/internalExchangeInfo.xml
> +									<ns2:version>LEVEL_a0</ns2
needs to https

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/test/resources/internalExchangeInfo.xml
> +									<ns2:version>LEVEL_a0</ns2
Needs to be https

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Common/Properties/src/main/resources/exchangeInfo.xml
> +                    <ns2:url>http://localhost:8181/Gateway/DocumentDataSubmission/1_0/DocumentRepositoryDocDataSubmission_Service</ns2:url>
this is an https url

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Gateway/DocumentDataSubmission_10/src/main/java/gov/hhs/fha/nhinc/docdatasubmission/outbound/OutboundDocDataSubmission.java
> +public interface OutboundDocDataSubmission {
Move this in to DDS core pacakge

2018-05-18 20:34 UTC, TabassumJafri commented on Product/Production/Gateway/DocumentDataSubmission_10/src/main/java/gov/hhs/fha/nhinc/docdatasubmission/outbound/PassthroughOutboundDocDataSubmission.java
> +public class PassthroughOutboundDocDataSubmission implements OutboundDocDataSubmission {
same as above

2018-05-21 12:22 UTC, plobre commented on Product/Production/Common/Properties/src/main/resources/exchangeInfo.xml
> +                    <ns2:url>http://localhost:8181/Gateway/DocumentDataSubmission/1_0/DocumentRepositoryDocDataSubmission_Service</ns2:url>
Good Catch. Missed this one.

2018-05-21 12:23 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/test/resources/internalExchangeInfo.xml
> +									<ns2:version>LEVEL_a0</ns2
These 3 comments are all on an Unsecured endpoint on 8080. Is there some reason why these 3 should use HTTPS? I would image the port would be using 8181 then if that were the case.

2018-05-21 13:43 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/test/resources/internalExchangeInfo.xml
> +									<ns2:version>LEVEL_a0</ns2
You can ignore these. However we don't need internalExchangeInfo and exchangeInfo in CONNECTAdminGUI src/test/resources folder

2018-05-21 19:00 UTC, plobre commented
Now dependent on https://github.com/CONNECT-Solution/CONNECT-Webservices/pull/43 from discussed WSDL Changes, so build will not pass until then.

2018-05-22 15:11 UTC, mhpnguyen commented
retest this please

2018-05-22 18:26 UTC, mhpnguyen requested changes

2018-05-22 18:26 UTC, mhpnguyen commented on Product/Production/Adapters/pom.xml
> +		<module>DocumentDataSubmission_a0</module>
Optional: remove tab or space so that it aligns with other.

2018-05-22 18:26 UTC, mhpnguyen commented on Product/Production/Common/Properties/src/main/resources/exchangeInfo.xml
> +              <ns2:name>DocDataSubmission</ns2:name>
Why we have two different endpoint name DocDataSubmission vs DocumentDataSubmission).  Make sure we use the same name

2018-05-22 18:26 UTC, mhpnguyen commented on Product/Production/Gateway/DocumentDataSubmission_10/src/main/resources/documentdatasubmission10.properties
> +docdatasubmission.inboundDocDataSubmission=gov.hhs.fha.nhinc.docdatasubmission.inbound.StandardInboundDocDataSubmission
move this into gateway.properties and remove this property

2018-05-22 18:26 UTC, mhpnguyen commented on Product/Production/Gateway/DocumentDataSubmission_10/src/main/resources/docdatasubmission/_10/applicationContext.xml
> +                <value>classpath:documentdatasubmission10.properties</value>
no need to use this properties since our gateway.properties already holds those values

2018-05-22 18:37 UTC, TabassumJafri requested changes

2018-05-22 18:37 UTC, TabassumJafri commented on Product/Production/Common/Properties/src/main/resources/exchangeInfo.xml
> +              <ns2:name>DocumentDataSubmission</ns2:name>
Need only one endpoint DocumentDataSubmission or DocDataSubmission. Please confirm on the service name as well.

2018-05-22 18:37 UTC, TabassumJafri commented on Product/Production/Common/Properties/src/main/resources/internalExchangeInfo.xml
> -</ns2:endpointConfigur
Can we rename it to adaptercomponenetXDSservice

2018-05-22 18:37 UTC, TabassumJafri commented on Product/Production/Common/Properties/src/main/resources/internalExchangeInfo.xml
> -</ns2:endpointConfigur
use xds instead of dds

2018-05-22 18:37 UTC, TabassumJafri commented on Product/Production/Services/DocumentDataSubmissionCore/src/main/java/gov/hhs/fha/nhinc/docdatasubmission/outbound/StandardOutboundDocDataSubmission.java
> +package gov.hhs.fha.nhinc.docdatasubmission.outbound;
No connect license

2018-05-22 18:45 UTC, TabassumJafri commented on Product/Production/Common/Properties/src/main/resources/internalExchangeInfo.xml
> -</ns2:endpointConfigur
update dds to xds here

2018-05-22 19:18 UTC, mhpnguyen commented on Product/Production/Common/Properties/src/main/resources/internalExchangeInfo.xml
> +                            <ns2:name>adapterdxsservice</ns2:name>
spelling. It should be adapterxdsservice

2018-05-22 19:34 UTC, mhpnguyen approved these changes

2018-05-22 19:35 UTC, TabassumJafri approved these changes

2018-05-22 19:55 UTC, merged