Conn 2171: Adding Doc Data Validation tests
CONNECT-Solution/CONNECT pull request #1663
Opened 2018-05-25 17:52 UTC by plobre

2018-05-25 20:06 UTC, TabassumJafri requested changes

2018-05-25 20:06 UTC, TabassumJafri commented on Product/SoapUI_Test/ValidationSuite/ConnectValidation-soapui-project.xml
> +
Need to add nhinTargetCommunities

2018-05-25 20:06 UTC, TabassumJafri commented on Product/SoapUI_Test/ValidationSuite/ConnectValidation-soapui-project.xml
> +              <con:selectedAuthProfile>Basic</con:selectedAuthProfile><con:addedBasicAuthenticationTypes>Basic</con:addedBasicAuthenticationTypes><con:authType>Global HTTP Settings</con:authType>
Do we need selectedAuthProfile?

2018-05-30 12:32 UTC, plobre commented
On hold until DDS services get created due to new requirements for validation suite tests.

2018-05-31 15:18 UTC, closed without merging