CONN-2207 clean-up-unused-code
CONNECT-Solution/CONNECT pull request #1694
Opened 2018-07-06 17:49 UTC by trantang

removing the nhinc-component-manager along with UDDI-file-and-server-refresh

2018-07-06 17:55 UTC, plobre approved these changes

2018-07-06 18:08 UTC, ptambellini01 approved these changes

2018-07-06 18:51 UTC, mhpnguyen requested changes
You also miss the cxf configuration
https://github.com/CONNECT-Solution/CONNECT/blob/c45a4182fc1ae95bf2e9bdecb87c22dcc86629ae/Product/Production/Common/CONNECTCommonWeb/src/main/webapp/WEB-INF/cxf-servlet.xml#L20

2018-07-10 19:17 UTC, mhpnguyen approved these changes

2018-07-10 19:24 UTC, plobre approved these changes

2018-07-10 19:34 UTC, merged