Conn 2172 - Patient Location Query Adapter
CONNECT-Solution/CONNECT pull request #1697
Opened 2018-07-11 15:41 UTC by plobre

https://github.com/CONNECT-Solution/CONNECT-Webservices/pull/48 needs to be merged first in order for this to compile / pass as it relies on WSDL changes

2018-07-11 15:50 UTC, plobre commented on Product/Production/Common/Properties/src/main/resources/audit.properties
> +#A Boolean value to set Document Data Submission audit logging on or off
DDS Copy Pasta here. Need to go and change this to read PLQ instead.

2018-07-11 16:55 UTC, plobre commented
retest this please

2018-07-11 17:11 UTC, trantang requested changes

2018-07-11 17:11 UTC, trantang commented on Product/Production/Common/CONNECTCoreLib/src/test/java/gov/hhs/fha/nhinc/patientlocationquery/adapter/dao/PatientLocationQueryDaoIntTest.java
> +        List<RecordLocatorService> result = RecordLocationServiceDAO.getAllPatientsBy("111222");
SQL script for RecordLocationService--requestedPatientId are 1, 2, 3, 4, 5
this would fail if records are not in the database `testGetAllByRLSId`

2018-07-11 17:17 UTC, TabassumJafri requested changes

2018-07-11 17:17 UTC, TabassumJafri commented on Product/DBScripts/nhincdb/nhincdb.sql
> +CREATE TABLE IF NOT EXISTS patientcorrelationdb.correlatedidentifiers (
Need to update nhincdb_oracle.sql script as well

2018-07-11 17:17 UTC, TabassumJafri commented on Product/Production/Adapters/PatientDiscovery_a0/src/main/java/gov/hhs/fha/nhinc/patientlocationquery/adapter/AdapterPatientLocationQuerySecured.java
> +        context.toString();
Do we need this?

2018-07-11 17:17 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/patientcorrelation/nhinc/model/RecordLocatorService.java
> +package gov.hhs.fha.nhinc.patientcorrelation.nhinc.model;
Need to add CONNECT license

2018-07-11 17:17 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/patientlocationquery/dao/RecordLocationServiceDAO.java
> + *
Missing CONNECT License

2018-07-11 17:17 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientlocationquery/aspect/AdapterPatientLocationQueryBaseEventDescriptionBuilder.java
> + * Copyright (c) 2009-2018, United States Government, as represented by the Secretary of Health and Human Services.
Why we need this class when we are not using it events annotation?

2018-07-11 17:17 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientlocationquery/aspect/AdapterPatientLocationQueryResponseTypeHolderBuilder.java
> +/*
Why this class is needed when we are not using it in event annotation?

2018-07-11 17:17 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientlocationquery/services/PatientLocationQuery.java
> + *
No CONNECT License

2018-07-11 17:17 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientlocationquery/services/PatientLocationQueryImpl.java
> + *
No CONNECT License

2018-07-11 17:22 UTC, plobre commented on Product/Production/Adapters/PatientDiscovery_a0/src/main/java/gov/hhs/fha/nhinc/patientlocationquery/adapter/AdapterPatientLocationQuerySecured.java
> +        context.toString();
Nope. Will remove.

2018-07-12 12:23 UTC, trantang approved these changes

2018-07-12 13:23 UTC, TabassumJafri requested changes

2018-07-12 13:23 UTC, TabassumJafri commented on Product/DBScripts/nhincdb/nhincdb_oracle.sql
> +--------------------------------------------------------
Need to update CorrelatedIdentifiers table with RlsId

2018-07-12 13:23 UTC, TabassumJafri commented on Product/Production/Services/PatientDiscoveryCore/src/main/java/gov/hhs/fha/nhinc/patientlocationquery/adapter/proxy/AdapterPatientLocationQueryProxyObjectFactory.java
> +
CONNECT License comes before package declaration

2018-07-12 13:50 UTC, TabassumJafri approved these changes

2018-07-12 14:00 UTC, merged