Assertion GUI
CONNECT-Solution/CONNECT pull request #1698
Opened 2018-07-12 17:07 UTC by jsmith2

Updates for linking assertion data to user and adding purposeOf option for Patient Query workflow.

-- DO NOT MERGE

2018-10-01 18:59 UTC, TabassumJafri commented
Need to update nhincdb_oracle.sql

2018-10-01 19:02 UTC, TabassumJafri requested changes

2018-10-01 19:02 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/resources/roleCodes.properties
> +Specialized_surgeon=1421009
We need roleCode.properties only in one place.

2018-10-01 19:10 UTC, trantang approved these changes

2018-10-01 19:10 UTC, trantang commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/PatientSearchBean.java
> +                "Error:  " + userName + "does not have valid assertion data.", "Login as a valid user."));
missing space before "does"

2018-10-01 19:56 UTC, plobre approved these changes

2018-10-01 19:56 UTC, plobre commented
Aside from the 2 comments so far, looks good.

2018-10-01 20:02 UTC, ptambellini01 approved these changes

2018-10-11 18:05 UTC, TabassumJafri commented
Closing PR in favor of  https://github.com/CONNECT-Solution/CONNECT/pull/1776

2018-10-11 18:05 UTC, closed without merging