CONN-2246 Ping-error and Timeout-issue
CONNECT-Solution/CONNECT pull request #1731
Opened 2018-08-10 17:15 UTC by trantang

add Ping-error status to Dashboard ping service
skip Ping-service-url if the host is known-for-timeout issue

2018-08-10 17:30 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/model/ConnectionEndpoint.java
> +    public boolean isPass() {
Can we name this to something a bit more meaningful, such as "isResponding" or "returnedOK"?

2018-08-10 19:04 UTC, plobre requested changes

2018-08-10 19:04 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/services/impl/PingServiceImpl.java
> +        LOG.info("Timeout-servers-list is resetted");
Get rid of the -'s in the log.

2018-08-10 19:04 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/services/impl/PingServiceImpl.java
> +                LOG.warn("skip-known-timeout-server-host: {}", url);
Get rid of  the -'s. Also should this be a warning? It seems desired that we skip it, so why not log this at Debug or Trace level?

2018-08-13 13:03 UTC, TabassumJafri requested changes

2018-08-13 13:03 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/services/impl/PingServiceImpl.java
> +    public static final boolean DO_NOT_IGNORE_DEADHOST = false;
No need for DO_NOT_IGNORE_DEADHOST. This can be simply negated with IGNORE_DEADHOST

2018-08-13 14:15 UTC, TabassumJafri approved these changes

2018-08-13 14:19 UTC, plobre approved these changes

2018-08-13 14:46 UTC, ptambellini01 approved these changes

2018-08-13 14:48 UTC, merged