CONN-2260b fix-jmx methods
CONNECT-Solution/CONNECT pull request #1744
Opened 2018-08-23 19:59 UTC by trantang

jmx methods was disable and the test-case hang on the mock-service

2018-08-23 20:05 UTC, TabassumJafri requested changes

2018-08-23 20:05 UTC, TabassumJafri commented on Product/SoapUI_Test/RegressionSuite/Passthru/AuditLogging-Passthrough/AuditLogging-Passthrough-soapui-project.xml
> +      <con:value>C:\_development\Servers\wildfly-8.2.1.Final\modules\system\layers\base\org\connectopensource\configuration\main</con:value>
remove this

2018-08-23 20:33 UTC, vdmehta06 approved these changes

2018-08-24 12:26 UTC, plobre approved these changes

2018-08-24 13:05 UTC, TabassumJafri approved these changes

2018-08-24 13:10 UTC, ptambellini01 approved these changes

2018-08-24 13:11 UTC, merged