Conn 2264 MemoryLeak JMX and Soapui
CONNECT-Solution/CONNECT pull request #1752
Opened 2018-09-05 16:41 UTC by trantang

adding debug-statement for JMX and CONNECT-Services
including Webservice-bean into Spring applicationContext
Fixed the missing attributes from soapui-tests

2018-09-05 16:54 UTC, plobre requested changes
I don't understand the reasoning behind some of these changes. Why are we debugging App Contexts in a DB Utility. I thought we had also decided that we wanted to see some logs when the PassthuMXBeanRegistry actually sets the services to either Standard/Passthrough, but I don't see any of that here

2018-09-05 16:54 UTC, plobre commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/util/GenericDBUtils.java
> +    public static <T> void debugApplicationContext(Class<T> from, ApplicationContext context) {
Why do we have all of this in the GenericDBUtils? It has nothing to do with the database.

2018-09-05 16:54 UTC, plobre commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/util/GenericDBUtils.java
> +                System.out.println(Arrays.toString(context.getBeanDefinitionNames()));
Why are we using SysOut here?

2018-09-05 16:54 UTC, plobre commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/util/GenericDBUtils.java
> +    public static <T> String toJsonString(T object) {
I don't see this being used at all.

2018-09-05 16:54 UTC, plobre commented on Product/Production/Services/AdminDistributionCore/src/main/java/gov/hhs/fha/nhinc/admindistribution/inbound/PassthroughInboundAdminDistribution.java
> +        GenericDBUtils.logInfoServiceProcess(this.getClass());
What is the point of all these logs here? "Flag service processing debug: PassthroughInboundAdminDistribution" would be outputted.

2018-09-05 16:59 UTC, plobre commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/util/GenericDBUtils.java
> +    public static <T> void debugServletContext(Class<T> from, ServletContext context) {
Not being used either

2018-09-05 20:00 UTC, plobre approved these changes

2018-09-06 14:02 UTC, TabassumJafri approved these changes

2018-09-06 14:09 UTC, merged