Conn 2226 validationSuite and g2g-nodejs
CONNECT-Solution/CONNECT pull request #1817
Opened 2018-11-20 21:03 UTC by trantang

update validationSuite to passed g2g-setup on nodejs
validationSuite-propety: `loopback` will allow test to skip out on step that design for loopback-mode only

2018-11-20 21:07 UTC, ptambellini01 approved these changes

2018-11-20 21:33 UTC, plobre approved these changes

2018-11-21 14:02 UTC, TabassumJafri requested changes

2018-11-21 14:02 UTC, TabassumJafri commented on Product/SoapUI_Test/ValidationSuite/ConnectValidation-soapui-project.xml
> +if(localAA == '1.1' &amp;&amp; remoteAA == '2.2'){
Is this if needed? Can we we use localAA and remoteAA directly in the query?

2018-11-21 14:02 UTC, TabassumJafri commented on Product/SoapUI_Test/ValidationSuite/ConnectValidation-soapui-project.xml
> +          <con:value>false</con:value>
Why PassThruOn is changed to false?

2018-11-21 14:02 UTC, TabassumJafri commented on Product/SoapUI_Test/ValidationSuite/ConnectValidation-soapui-project.xml
> +if(loopback == 'true'){
I think we don't need to check loopback here. For standard mode, we will always have correlations in DB no matter if we are doing G2G or loopback

2018-11-21 15:15 UTC, trantang commented on Product/SoapUI_Test/ValidationSuite/ConnectValidation-soapui-project.xml
> +          <con:value>false</con:value>
PassthruOn is updated by script

2018-11-21 15:16 UTC, trantang commented on Product/SoapUI_Test/ValidationSuite/ConnectValidation-soapui-project.xml
> +if(localAA == '1.1' &amp;&amp; remoteAA == '2.2'){
the reason i omit this query-statement is that i don't know what is the expected result for the g2g

2018-11-21 15:17 UTC, trantang commented on Product/SoapUI_Test/ValidationSuite/ConnectValidation-soapui-project.xml
> +if(loopback == 'true'){
this is FAILED on G2G so i check for loopback to skip the assertion

2018-11-21 16:38 UTC, TabassumJafri approved these changes

2018-11-21 16:42 UTC, mhpnguyen approved these changes

2018-11-21 16:42 UTC, merged