CONN-2017/CONN-2375 config gateway with multiple SSL/Certs
CONNECT-Solution/CONNECT pull request #1830
Opened 2018-12-14 14:27 UTC by trantang

allow configuration to multiple-ssl-certificates to support multiple communities without restarting connect-gateway server.

2018-12-14 16:26 UTC, plobre commented
retest this please

2018-12-14 18:57 UTC, plobre approved these changes

2018-12-14 20:14 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
> +            X509Certificate publicCert = getDefaultCertificate(null);
why is the alias null  for this getDefaultCertificate() call?

2018-12-14 20:40 UTC, trantang commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
> +            X509Certificate publicCert = getDefaultCertificate(null);
get-default-certifciate by null will return the default certificate;
but the issue now is the multiple certicates that are default gateway and gateway_b

2018-12-14 20:54 UTC, trantang commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
> +            X509Certificate publicCert = getDefaultCertificate(null);
default certificate mapped `CLIENT_KEY_ALIAS`

2018-12-14 22:06 UTC, mhpnguyen requested changes

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/cryptostore/StoreUtil.java
> +                LOG.debug("debug--found url:{}, gatewayAlias:{}", url, gatewayAlias);
Optional: remove "debug" in print statement.

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/cryptostore/StoreUtil.java
> +     * to successfully add the gatewayAlias it url and alias cannot be blank and alias cannot be CLIENT_KEY_ALIAS
Make javadoc more clear on what this method does.  It seems the method does two different things: update the internal hashmap and return the request.  Maybe try to separate out into different methods or rename method

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/cryptostore/StoreUtil.java
> +                    LOG.debug("debug--remove:urlKey:{}", urlKey);
Remove "debug" print statement.

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManager.java
> +    public abstract X509Certificate getDefaultCertificate(String alias) throws CertificateManagerException;
Recommend to create different method to retrieve cert based on alias.  The name is ambitious since if I don't pass parameter, it should get default.

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManager.java
> +    public abstract PrivateKey getDefaultPrivateKey(String alias) throws CertificateManagerException;
Recommend to create new method to get private key based on alias.

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManager.java
> +    public abstract RSAPublicKey getDefaultPublicKey(String alias);
Similar here as above

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
> +        LOG.debug("debug -- CertificateManagerImpl-getDefaultCertificate:{}", alias);
No need to put debug statement in print statement.

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
> +        LOG.debug("debug -- CertificateManagerImpl-getDefaultPrivateKey:{}", alias);
remove debug statement

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
>          KeyStore.PrivateKeyEntry pkEntry = null;
Optional: What wrong with using PrivateKeyEntry instead of KeyStore.PrivateKeyEntry?

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
>          if (clientkeyAlias != null) {
Optional: based on the current workflow, clientKeyAlias will never be null.  If so, remove conditional check

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
> +            X509Certificate publicCert = getDefaultCertificate(null);
We should return a list of default cert instead of single one if we are enable this feature.

2018-12-14 22:06 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchangemgr/AbstractExchangeManager.java
> +                    return StoreUtil.addGatewayAlias(ExchangeManagerHelper.getEndpointURLBySpecVersion(
Recommend to divide into 2 method.  one for save internal hashmap and other for return url after lookup. For example:
String url = ExchangeManagerHelper.getEndpointURLBySpecVersion(epType.getEndpointConfigurationList(),higestAPI);
StoreUtil.addGatewayAlias(url,getGatewayAlias(exchangeName))

2018-12-17 15:52 UTC, TabassumJafri requested changes

2018-12-17 15:52 UTC, TabassumJafri commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
> +    public X509Certificate getDefaultCertificate(String alias) throws CertificateManagerException {
Can we rename this method getDefaultCertificate to something more appropriate comething along these lines getCertificateFor /getCertificateBasedOn

2018-12-17 18:34 UTC, ptambellini01 approved these changes

2018-12-17 18:34 UTC, mhpnguyen requested changes

2018-12-17 18:34 UTC, mhpnguyen commented on Product/SoapUI_Test/ValidationSuite/exchangeInfo_g1.xml
> +      <certificateAlias>gateway</certificateAlias>
Remove it.

2018-12-17 18:34 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateManagerImpl.java
> +                LOG.error("Error initializing Private Keys: {}", ex.getLocalizedMessage(), ex);
Optional: No need to log since we throw the exception here. The caller will catch and log it.

2018-12-17 18:36 UTC, TabassumJafri approved these changes

2018-12-17 19:14 UTC, mhpnguyen approved these changes

2018-12-17 19:15 UTC, merged