fixed Auditloging to pick userId from Certificate's Subject DN
CONNECT-Solution/CONNECT pull request #1834
Opened 2018-12-18 19:07 UTC by TabassumJafri

Updated AuditTransform class to pull userID from certificate Subject DN.
Fixed junit tests
Updated properties in AuditLogging Standard/Passthru RegressionSuites.

2018-12-18 20:50 UTC, trantang commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/exchangemgr/ExchangeManagerHelper.java
> +    public static String getExchangeAlias(String exchangeName) {
exchangeManager.getGatewayAlias

however the internalExchangeManager.getGatewayAlias will return an null and will default:CIENT_KEY_ALIAS

2018-12-19 13:34 UTC, plobre requested changes

2018-12-19 13:34 UTC, plobre commented on Product/Production/Services/AuditRepositoryCore/src/main/java/gov/hhs/fha/nhinc/audit/transform/AuditTransforms.java
> +    private static boolean checkDistinguishedName(String userName) {
We have this exact method already in HOKSAMLAssertionBuilder. Could we extract this to a shared utility class instead of duplicating code here?

2018-12-19 13:34 UTC, plobre commented on Product/Production/Services/AuditRepositoryCore/src/test/java/gov/hhs/fha/nhinc/audit/transform/AuditTransformsTest.java
> -            assertEquals("UserID mismatch", assertion.getUserInfo().getUserName(), userActiveParticipant.getUserID());
Why are we loosening this test? Seems we knew the User ID before this change. Is it no longer possible to match this on the passed in assertion

2018-12-19 13:34 UTC, plobre commented on Product/Production/Services/CORE_X12DocumentSubmissionCore/src/test/java/gov/hhs/fha/nhinc/corex12/ds/audit/transform/X12BatchAuditTransformsTest.java
> +    @Ignore
Is this Ignore intentional?

2018-12-19 15:19 UTC, trantang approved these changes

2018-12-19 21:15 UTC, mhpnguyen approved these changes

2018-12-20 14:31 UTC, plobre commented on Product/Production/Services/DocumentQueryCore/src/test/java/gov/hhs/fha/nhinc/docquery/audit/transform/DocQueryAuditTransformsTest.java
> +        //final CertificateManager certMgr = getCertificateMgr();
Commented out code?

2018-12-20 14:32 UTC, plobre commented on Product/Production/Services/DocumentQueryCore/src/test/java/gov/hhs/fha/nhinc/docquery/audit/transform/DocQueryAuditTransformsTest.java
> +        //initialize();
Same here - Can we remove the comment?

2018-12-20 14:41 UTC, plobre approved these changes

2018-12-20 15:14 UTC, ptambellini01 approved these changes

2018-12-20 15:15 UTC, merged