Add support Admingui in FIP mode
CONNECT-Solution/CONNECT pull request #1836
Opened 2018-12-19 21:10 UTC by mhpnguyen

Optional : @jsmith2

2018-12-19 21:18 UTC, TabassumJafri requested changes

2018-12-19 21:18 UTC, TabassumJafri commented on Product/Production/Common/Properties/src/main/resources/admingui.properties
> +jsf.algorithm=AES
Can we add description/comments for these properties?

2018-12-19 21:18 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/servlet/CustomServletListener.java
> +        if (secret != null) {
Do we need to specify all these properties. If yes can we && these  values

2018-12-19 21:23 UTC, jsmith2 commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/servlet/CustomServletListener.java
> +        LOG.debug("Calling Custom contextInitialized");
Should be trace level.

2018-12-20 15:38 UTC, ptambellini01 approved these changes

2018-12-20 20:25 UTC, TabassumJafri approved these changes

2018-12-20 20:34 UTC, plobre approved these changes

2018-12-20 20:35 UTC, trantang approved these changes

2018-12-20 20:36 UTC, merged