Conn 2386 - Configurable SAML Signature
CONNECT-Solution/CONNECT pull request #1841
Opened 2019-01-04 19:05 UTC by plobre

Adds 4 new properties to gateway.properties:

- saml.signatureAlgorithms = list of supported algorithms for signing the signature
- saml.digestAlgorithms = list of supported algorithms for the digest method
- saml.defaultSignatureAlgorithm = default algorithm to be used to sign the signature
- saml.defaultDigestAlgorithm = default algorithm for the digest method.

Also allows the Entity message to specify a requested algorithm in the assertion block. 

Relies on https://github.com/CONNECT-Solution/Common-Types/pull/89

2019-01-04 20:07 UTC, mhpnguyen requested changes

2019-01-04 20:07 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/SAMLUtils.java
> +        return assertion != null && !StringUtils.isBlank(assertion.getSignatureAlgorithm()) ?  assertion.getSignatureAlgorithm() : getSignatureAlgorithm();
Optional: Try to use StringUtils.isNotBlank instead of ! StringUtil.isBlank

2019-01-04 20:07 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/SAMLUtils.java
> +        return assertion != null && !StringUtils.isBlank(assertion.getDigestAlgorithm()) ?  assertion.getDigestAlgorithm() : getDigestAlgorithm();
Try to use StringUtils.isNotBlank

2019-01-04 20:07 UTC, mhpnguyen commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/util/NhinUtils.java
> +            LOG.error("Invalid distinguished name {}", userName);
change debug to warn or error. No need to include both inside here

2019-01-04 20:26 UTC, TabassumJafri approved these changes

2019-01-04 20:37 UTC, plobre commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/cxf/wss/CONNECTSignatureProcessor.java
> +            && digestAlgorithms.size() == 1 && SignatureConstants.ALGO_ID_DIGEST_SHA1.equals(digestAlgorithms.get(0));
Not true for either of these, as getConfigurableSHA() will always at least 1 element - which also technically means line 91 is not needed now that I think about it.

Will throw in a null check anyway.

2019-01-04 21:11 UTC, mhpnguyen approved these changes

2019-01-04 21:25 UTC, ptambellini01 approved these changes

2019-01-07 15:04 UTC, trantang approved these changes

2019-01-07 19:37 UTC, merged