Conn 2410 - Deferred Document Query stubs
CONNECT-Solution/CONNECT pull request #1880
Opened 2019-03-08 18:28 UTC by plobre

Adds basic stubs / bindings to CONNECT and a new "DDQ" profile for building DDQ web services and bundling into EAR.

2019-03-08 18:52 UTC, plobre commented
Awaiting Webservices to be merged. Validation Suite wont pass without it.

2019-03-11 12:15 UTC, plobre commented
retest this please

2019-03-11 14:01 UTC, TabassumJafri requested changes

2019-03-11 14:01 UTC, TabassumJafri commented on Product/Production/Adapters/DocumentQueryDeferred_a0/src/main/webapp/WEB-INF/web.xml
> +    <login-config>
What is this used for?

2019-03-11 14:01 UTC, TabassumJafri commented on Product/Production/Deploy/pom.xml
> +          <!-- DQ -->
Fix the comments

2019-03-11 14:01 UTC, TabassumJafri commented on Product/Production/Adapters/DocumentQueryDeferred_a0/pom.xml
> +            <groupId>org.jmock</groupId>
remove these unused jmock dependencies

2019-03-11 14:01 UTC, TabassumJafri commented on Product/Production/Adapters/DocumentQueryDeferred_a0/pom.xml
> +            <groupId>org.connectopensource</groupId>
Don't think adapter will need AuditRepositoryCore dependency at runtime. Remove it for now and when we implement Audit logging we can add back in if needed

2019-03-11 14:01 UTC, TabassumJafri commented on Product/Production/Gateway/DocumentQueryDeferred_10/pom.xml
> +            <artifactId>DocRegistryCore</artifactId>
Don't think we will need this for gateway project.

2019-03-11 14:26 UTC, ptambellini01 approved these changes

2019-03-11 14:40 UTC, trantang approved these changes

2019-03-11 14:47 UTC, TabassumJafri approved these changes

2019-03-11 14:49 UTC, merged