CONN-2437 import wizard part2
CONNECT-Solution/CONNECT pull request #1881
Opened 2019-03-11 16:18 UTC by trantang

next four-tabs

2019-03-11 16:56 UTC, plobre commented on Product/Production/Common/CONNECTCoreLib/src/main/java/gov/hhs/fha/nhinc/callback/opensaml/CertificateUtil.java
> +            throw new CertificateManagerException("Empty alias or password for the keystore.");
Is it a requirement that a keystore must have a password to use CONNECT? You can have a blank password for a JKS.

2019-03-12 16:25 UTC, TabassumJafri requested changes

2019-03-12 16:25 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +            HelperUtil.addMessageError(null, "Alias and Server upload are required.");
Make message more clear

2019-03-12 16:25 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +            HelperUtil.addMessageError(null, "Alias, Intermediate and Root are required.");
Make message more clear

2019-03-12 16:25 UTC, TabassumJafri commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +        return buildSimpleResponse(true, "import temporary truststore successful.");
Make message more clear

2019-03-12 16:25 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/webapp/certificateManager.xhtml
> +                                            <h:outputText>Go to your selected CA Authority website and enter the authorization code and the reference number.
Update message like this: "Go to your selected CA Authority website and enter the authorization code and reference number. Follow instructions to generate certificate. Copy the generated certificate  and ??"

2019-03-12 19:01 UTC, TabassumJafri approved these changes

2019-03-12 19:14 UTC, ptambellini01 approved these changes

2019-03-12 19:27 UTC, plobre approved these changes

2019-03-12 19:27 UTC, merged