CONN-2440 completing import wizard
CONNECT-Solution/CONNECT pull request #1887
Opened 2019-03-25 13:44 UTC by trantang

importWizard/backup
importWizard/new
importWizard/temp
manually replace the KeyStore and TrustStore and restart the server

2019-03-25 13:59 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/webapp/certificateManager.xhtml
> +                                            <h:outputText>Upon completing the import wizard the new KeyStore and TrustStore will be created under `importWizard/new` and the old KeyStore and TrustStor
Why do we have a total of 3 folders for this? I thought the criteria was to have everything under one folder.

2019-03-25 16:17 UTC, plobre requested changes
Only real issue is the message for the happy path on completing the import wizard. For everything else, what currently is committed is fine, with optional changes requested if possible.

2019-03-25 16:17 UTC, plobre commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +    private String getPathKeystore(String folder) {
Why are we doing all this logic when the full path is specified in the JVM `javax.net.ssl.keyStore` property? Also the keystore might not even be in the NHINC directory.

This comment also applies to the Trust Store.

2019-03-25 16:17 UTC, plobre commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +                "Please go to the server {0}. Go to importWizard/new, copy and replace the KeyStore and TrustStore (server restart required).",
"Please replace your existing KeyStore and TrustStore with the ones provided at '{0}/importWizard/new'. Note: A server restart may be required"

2019-03-25 16:17 UTC, plobre commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +            return buildSimpleResponse(false, "Error occured while backup KeyStore.");
Optional: I feel a more elegant approach would be to throw an exception here, and catch it. The Catch would read the exception message and build a simple response based on that.

2019-03-25 16:17 UTC, plobre commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +            return buildSimpleResponse(false, "Error while occurred cleaning up the import folders.");
Optional: Per previous comment, this would instead re-throw the IOException with a different message, and catch it later on.

2019-03-25 16:17 UTC, plobre commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +            return buildSimpleResponse(false, "Temporary folder does not exist.");
I wouldn't word the error this way - It doesn't tell the user anything meaningful. They won't know what the temporary folder has to do with the fact that they haven't seemed to have started an import.

I would say something like "Could not find certificate chain to import". Will have to ask the team for better suggestions, as I'm drawing a blank on how to word it. Essentially, just need to let them know that they may not have started the wizard, and may need to go back and redo the wizard.

2019-03-25 18:04 UTC, TabassumJafri requested changes

2019-03-25 18:04 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +            HelperUtil.addMessageError(null, "Error occured while calling completeImportWizard.");
Fix error message.

2019-03-25 18:04 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/webapp/certificateManager.xhtml
> +                                            <h:outputText>Upon completing the import wizard the new KeyStore and TrustStore will be created under `importWizard/new` and the old KeyStore and TrustStor
No mention of 'If AdminGUI is deployed remotely ..'

2019-03-25 18:04 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/webapp/certificateManager.xhtml
> +                                                        message="Completing the import wizard will create backup and new, and delete temporary (KeyStore and TrustStore). Do you wanted to continue?"
Continue with creating backup of existing KeyStore and TrustStore and saving newly constructed KeyStore and TrustStore?

2019-03-25 18:39 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/webapp/certificateManager.xhtml
> +                                            <h:outputText>Upon completing the import wizard the new KeyStore and TrustStore will be created under `importWizard/new` and the old KeyStore and TrustStor
Suggested Text:

Upon completion of the import wizard, a new KeyStore and TrustStore will be created under '/importWizard/new' and a backup of the KeyStore and TrustStore prior to importing will be copied to '/importWizard/backup'. The new KeyStore and TrustStore must be manually replaced with the ones provided in '/importWizard/new'. If the Admin GUI deployment is hosted on a container server independant of CONNECT, the KeyStore and TrustStore must be manually replaced there as well.

2019-03-26 12:29 UTC, trantang commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +            return buildSimpleResponse(false, "Temporary folder does not exist.");
The import process had not started yet

2019-03-26 13:28 UTC, trantang commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +    private String getPathKeystore(String folder) {
the only think the `javax.net.ssl.keyStore` provide is the filename; the `importWizard` is going to be created under NHINC directory we know we have access to this directory and permission i think; we will backup the KeyStore and TrustStore under `importWizard/backup` and create new KeyStore and TrustStore under `importWizard/new` as far as i can tell these folder are not part of the JVM

2019-03-26 14:03 UTC, plobre approved these changes

2019-03-26 14:08 UTC, ptambellini01 approved these changes

2019-03-26 15:47 UTC, TabassumJafri approved these changes

2019-03-26 16:00 UTC, merged