CONN-2446 Import wizard improvements
CONNECT-Solution/CONNECT pull request #1892
Opened 2019-04-04 16:44 UTC by trantang

Resume tab
New Alias for new Certificate
soft-cancel call undo
clear intermediate chain on import

2019-04-04 18:00 UTC, plobre requested changes
Minor grammer mistakes.

2019-04-04 18:00 UTC, plobre commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +            return buildSimpleResponse(false, "Fail to retrieve aliases list");
Fail -> "Failed"
aliases -> alias

2019-04-04 18:00 UTC, plobre commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +            return buildSimpleResponse(false, "Undo import in KeyStore required Alias, CA Root and CA Intermediate.");
"Undoing an import requires the Alias, CA Root, and Intermediate certificates"

2019-04-04 18:00 UTC, plobre commented on Product/Production/Gateway/AdminGUIWebservices/src/main/java/gov/hhs/fha/nhinc/configadmin/ConfigAdmin.java
> +            return buildSimpleResponse(false, "Undo import in Truststore required Alias, CA Root and CA Intermediate.");
"Undoing an import requires the Alias, CA Root, and Intermediate certificates"

2019-04-04 18:00 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/webapp/certificateManager.xhtml
> +                                                        message="WARNING: This will remove upload CA certificates from temporary KeyStore, are you sure?"
"WARNING: This will remove uploaded certificates from the temporary KeyStore. Are you sure?"

2019-04-04 18:00 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/webapp/certificateManager.xhtml
> +                                                        message="WARNING: This will remove uploaded CA certificates from temporary TrustStore, are you sure?"
"WARNING: This will remove uploaded certificates from temporary TrustStore. are you sure?"

2019-04-04 18:31 UTC, TabassumJafri approved these changes

2019-04-04 19:10 UTC, ptambellini01 approved these changes

2019-04-05 14:11 UTC, plobre requested changes

2019-04-05 14:11 UTC, plobre commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/webapp/certificateManager.xhtml
> +                                            <h:outputText>The Import Wizard thru a couple of steps makes a certificate, sets up the Certificate Signing Request (CSR) and allows for the certificate to
thru -> through
Once, the certificate has been verified by the -> Remove comma after "Once"

2019-04-05 14:44 UTC, plobre approved these changes

2019-04-05 14:45 UTC, merged