CONN-2461 fix import-wizard QA
CONNECT-Solution/CONNECT pull request #1902
Opened 2019-05-03 13:19 UTC by trantang

fixing usability issue with import-wizard

2019-05-03 18:24 UTC, plobre approved these changes

2019-05-03 18:28 UTC, ptambellini01 approved these changes

2019-05-03 18:52 UTC, TabassumJafri requested changes

2019-05-03 18:52 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +            "CA Providers", "KeyStore/TrustStore" };
Can we say Import to KeyStore and TrustStore?

2019-05-03 18:52 UTC, TabassumJafri commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +        if(MapUtils.isNotEmpty(listIntermediate) && null == uploadedFileRoot){
Are we importing server's public certificate to keystore as well?

2019-05-06 14:08 UTC, sailajaa commented
Improvement: Certificate Management - Start Tab: make 'certificate' as common case sense in all 3 links

2019-05-06 14:37 UTC, TabassumJafri approved these changes

2019-05-06 14:37 UTC, merged