Conn 2454 - Deferred Response Option Query
CONNECT-Solution/CONNECT pull request #1903
Opened 2019-05-03 18:17 UTC by plobre

Adds the IG's Deferred response option query to store the request ID, DC ID, and the desired endpoint to respond to.

2019-05-03 18:43 UTC, TabassumJafri requested changes

2019-05-03 18:43 UTC, TabassumJafri commented on Product/Production/Gateway/DocumentQuery_30/src/main/java/gov/hhs/fha/nhinc/docquery/_30/entity/DeferredDocQueryCheck.java
> +public final class DeferredDocQueryCheck extends BaseService {
Why we are extending this class from BaseService?

2019-05-03 18:43 UTC, TabassumJafri commented on Product/Production/Services/DocumentQueryCore/src/main/java/gov/hhs/fha/nhinc/docquery/deferred/impl/AdapterDeferredResponseOptionImpl.java
> +    private static String saveRequest(AdhocQueryRequest msg, AssertionType assertion) {
Optional: this method is just confusing. We are calling it SaveRequest but a new Id is generated and returned here.

2019-05-03 19:14 UTC, trantang approved these changes

2019-05-03 20:49 UTC, ptambellini01 approved these changes

2019-05-06 17:31 UTC, TabassumJafri approved these changes

2019-05-06 17:31 UTC, merged