Conn 2471b - Code fixes for Admin GUI
CONNECT-Solution/CONNECT pull request #1917
Opened 2019-05-21 19:51 UTC by plobre

Fixes reported issues during QA for CONN 2471

2019-05-21 20:55 UTC, TabassumJafri approved these changes

2019-05-22 12:29 UTC, trantang requested changes

2019-05-22 12:29 UTC, trantang commented on Product/Production/Adapters/General/CONNECTAdminGUI/src/main/java/gov/hhs/fha/nhinc/admingui/managed/CertficateBean.java
> +                HelperUtil.addMessageError("deletePassKeyErrorMsg", response.getMessage());
use static variable

2019-05-22 12:36 UTC, ptambellini01 approved these changes

2019-05-22 12:48 UTC, trantang approved these changes

2019-05-22 12:48 UTC, merged